### ISSUE TITLE
Sending IP Address

### ISSUE THREAD

**Issue by bwatkins79** [cosullivan/SmtpServer#1]
Is it possible to get the IP address of the sender of an email that gets received by this smtp server?

**Comment by cosullivan** [comment]
Yes, in the IMailboxFilter you can override the CreateSessionInstance which is passed in the EndPoint of the connecting client.

**Comment by bwatkins79** [comment]
Thanks for the reply, i'm newer at this, would you mind giving an example?

**Comment by cosullivan** [comment]
Hi, I assume that you want the IP address such that you can filter the incoming requests based on a blacklist of some sort?

You would first register an instance of an `IMailboxFilter` during the creation of the SmtpServerOptions. If your instance of an IMailboxFilter overrides the CreateSessionInstance method then you can create a new instance of that filter specifically for that remote endpoint. 

Take the following example which only allows remote connections from Localhost.

```
public sealed class SimpleFilter : IMailboxFilter
{
    readonly IPEndPoint _remoteEndPoint;

    public SimpleFilter() { }

    SimpleFilter(IPEndPoint remoteEndPoint)
    {
        _remoteEndPoint = remoteEndPoint;
    }

    public IMailboxFilter CreateSessionInstance(EndPoint remoteEndPoint)
    {
        return new SimpleFilter((IPEndPoint)remoteEndPoint);
    }

    public Task<MailboxFilterResult> CanAcceptFromAsync(IMailbox @from, int size = 0)
    {
        if (_remoteEndPoint.Address.Equals(IPAddress.Parse("127.0.0.1")))
        {
            return Task.FromResult(MailboxFilterResult.Yes);
        }

        return Task.FromResult(MailboxFilterResult.NoPermanently);
    }

    public Task<MailboxFilterResult> CanDeliverToAsync(IMailbox to, IMailbox @from)
    {
        return Task.FromResult(MailboxFilterResult.Yes);
    }
}
```

**Comment by bwatkins79** [comment]
Thanks, I was able to get it working based off of this!
