### ISSUE TITLE
Error to run the example after build

### ISSUE THREAD

**Issue by khoaho** [cosullivan/SmtpServer#10]
I got the error "Transaction failed. The server response was: " at line 92 of Program.cs:

https://github.com/cosullivan/SmtpServer/blob/master/Src/SampleApp/Program.cs#L92

Can you please explain it.

Thank you

**Comment by cosullivan** [comment]
Hi,

That error will be coming from the mail client, but you will have to step through it to see if it is hitting the actual server or not and go from there.

Thanks,
Cain

**Comment by khoaho** [comment]
Hi Cain,

I stepped through the debugger and saw SmtpServer was created at http://0.0.0.0:9025. All methods in SmtpServer class were hit normally without error.

However, SmtpClient fails to send message. Here is the stack trace:


> at System.Net.Mail.DataStopCommand.CheckResponse(SmtpStatusCode statusCode, String serverResponse)
   at System.Net.Mail.DataStopCommand.Send(SmtpConnection conn)
   at System.Net.Mail.SmtpConnection.OnClose(Object sender, EventArgs args)
   at System.Net.ClosableStream.Close()
   at System.Net.Mail.MailWriter.Close()
   at System.Net.Mail.SmtpClient.Send(MailMessage message)
   at SampleApp.Program.<>c__DisplayClass2_1.<RunClientAsync>b__0() in C:\Data\GitHub\SmtpServer\Src\SampleApp\Program.cs:line 92
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

Line of error: https://github.com/cosullivan/SmtpServer/blob/master/Src/SampleApp/Program.cs#L92

Thanks.

**Comment by cosullivan** [comment]
Sorry, its really quite hard to guess what is going on here as the error is coming from the Mail Client. It looks as though it has something to do with the ending of the message, for example, when the mail client has finished sending the message content, it ends with a "<CRLF>.<CRLF>". This appears to be where its having trouble.

If you have a look at the DataCommand class (line 45) this is where it is reading the input from the stream and waiting for the "<CRLF>.<CRLF>" to finish the message so perhaps it is not working correctly from here. If you add a few break points on this while loop, does it finish correctly?

Thanks,
Cain

**Comment by khoaho** [comment]
I see the line 45 (of DataCommand class) was hit several times until getting "." to finish the message. Then it has error at line 92 (of Program class). Here is the message object at this point:

![image](https://cloud.githubusercontent.com/assets/1810890/17520851/d8e9720a-5e16-11e6-9b23-c20f08191cc7.png)

**Comment by khoaho** [comment]
...and the exception at SmtpClient:

![image](https://cloud.githubusercontent.com/assets/1810890/17521058/8ce3e272-5e17-11e6-9b55-0b7bfdebe383.png)

The SmtpServer object was created:

![image](https://cloud.githubusercontent.com/assets/1810890/17521161/f359f406-5e17-11e6-859a-29924d29d074.png)

**Comment by cosullivan** [comment]
Hi, OK so I finally had a chance to look at this - its actually working as expected :-) If you have a look at the ConsoleMessageStore this is returning the TransactionFailed response which is then passed back to the client. That was a recent change that I made and I must have left the TransactionFailed response code in there, but I have switched it back to the OK response code now for the sample.

Thanks,
Cain

**Comment by khoaho** [comment]
Hi Cain,

It works after you updated SmtpResponse.TransactionFailed to SmtpResponse.OK.

Can we send to the real email? At Program.cs, I change sample@test.com to my real email (at line 91), and comment out the while loop (at line 85, 86 & 110). But I don't see any email sent to my mailbox.

Thank you.

**Comment by cosullivan** [comment]
Hi,

I'm not 100% sure what you mean - this component though is the SMTP server component so it receives the messages, it doesn't send them on.

What mailbox are you referring to, your actual email account's mailbox?

The sample app uses the Mail client that is a part of the .NET Framework just for testing purposes.

Thanks,
Cain

**Comment by khoaho** [comment]
I use this code to send email (to an Outlook account) using Gmail SMTP server. Can we do the same with our local SmtpServer, to replace smtp.gmail.com with localhost?

```javascript
var smtpClient = new SmtpClient
	{
		Port = 587,
		Host = "smtp.gmail.com",
		EnableSsl = true,
		Timeout = 10000,
		DeliveryMethod = SmtpDeliveryMethod.Network,
		UseDefaultCredentials = false,
		Credentials = new System.Net.NetworkCredential("myemail@gmail.com", "password")
	};

MailAddress from = new MailAddress("from_email@outlook.com", "From Name");
MailAddress to = new MailAddress("to_email@outlook.com", "To Name");
MailMessage mail = new System.Net.Mail.MailMessage(from, to)
	{
		ReplyTo = new MailAddress(fromEmail),
		Subject = subject,
		SubjectEncoding = System.Text.Encoding.UTF8,
		Body = body,
		BodyEncoding = System.Text.Encoding.UTF8,
		IsBodyHtml = true
	};
smtpClient.Send(mail);
```

Thanks.

**Comment by cosullivan** [comment]
Hi, yes you can just replace smtp.gmail.com with localhost and it will send to the server running on localhost. However, this wont be sent anywhere else, it will just call into your IMessageStore implementation.

Thanks,
Cain

**Comment by khoaho** [comment]
Can you let the SmtpServer to send email in IMessageStore from localhost. I would love to see if you can have a local SMTP Server without using a remote SMTP Server.

Thank you.

**Comment by cosullivan** [comment]
Hi,

If you wanted to use it as an MTA (Mail Transport Agent) then you would have to on send it to another mail server anyway so I'm not really sure what you are looking for.

This component is purely just an SMTP server, so it will handle the communication with a Mail Client and then pass the resulting message context through to your own IMessageStore implementation. 

Thanks,
Cain

**Comment by khoaho** [comment]
Hi Cain,

Thank you to let me know that. As this SmtpServer is not an MTA so it will store messages only, not send messages.

We can close this issue. Thank you.

-Khoa
