### ISSUE TITLE
Can we make limited connection for particular user

### ISSUE THREAD

**Issue by vesnaveen** [cosullivan/SmtpServer#102]
We have to set  limited connection of the user who use to send mail. Suppose our limitation is 5 for one user. This user cannot create more than 5 parrell  connection at a time. 
If there is logic in your code or are you know about this type of situation. Please let me know.

Thanks

**Comment by cosullivan** [comment]
Hi,

Assuming you are able to keep track of the concurrent sessions externally to the server implementation, ie, your own cache for example, then it can be achieved in one of two places. 

Firstly, if the user has to authenticate against the mail server then it will call the AuthenticateAsync method of your custom IUserAuthenticator implementation. From within this you can do 

    throw new SmtpResponseException(SmtpReplyCode.ServiceUnavailable);

Alternatively, a custom implementation of the IMailboxFilter can be used and you can throw the same exception in the CanAcceptFromAsync method here. 

Thanks,
Cain.

**Comment by vesnaveen** [comment]
Okay cosullivan, I got it.
Thanks for your response.
