### ISSUE TITLE
Performance Issues - CPU exhaustion at relatively low throughput

### ISSUE THREAD

**Issue by giantjunkbox** [cosullivan/SmtpServer#104]
Thank you for this library, it seems well constructed and I learned a few things from studying it.

I have a project in which I'm attempting to construct an SMTP gateway which is capable of processing upwards of 1 million short messages per minute. I have the project, more or less, roughed out and this library is a great fit... almost....

During initial performance testing it became apparent that I can receive at most 1,000 messages per second. To keep things simple the testing is done using persistent connections to avoid the long TIME_WAIT issues that have come up before and a relative small number of threads - as in under 25.

Using basic monitoring tools it seems that the simple SMTP server app is using around 6 cores of CPU at 1,000 messages per second and CPU is the bottleneck. Bypassing any of the non-SMTP processing logic had a negligible impact.

The Visual Studio's performance profile reports that almost all of the CPU time is spent on various async methods. I am unclear if there are limits with the performance profiler and async in which it is unable to accurately report where the CPU time is being spent.

While I understand the underpinnings of async reasonably well, I do not have a great deal of experience actually using it for anything useful. In doing research it seems that there is a fairly significant overhead in using async/await. I've seen recommendations suggesting that async/await is best used with coarser (larger) methods and if there are many small methods they should be combined to minimize the performance overhead. I've also seen suggestions that there is somewhere around a 50ms penalty for using async/await and it should only be used if the operation is expected to take longer then that.

To help understand where the bottleneck is I hacked out just about all of the async/await stuff and largely rejiggered the library to be a synchronous server.  After doing this I am able to process somewhere around 20,000 messages per second. I am admittedly not entirely confident that I did not break something else along the way... I still need to do a lot of testing and rework.

I am somewhat unclear if this is just a single async/await method that is getting called thousands of times per seconds or if this is more of an issue with the combination of all of them.

Is there a reason there is so much async/await in this library vs just spinning each new connection off to a separate thread?

Would you be receptive to a pull request that largely eliminated much of the async/await code if it included a huge performance increase? Notably some of the public interface methods return Task objects. Depending how far this went, compatibility might break.

Thank you

**Comment by cosullivan** [comment]
Hi,

I wouldn't be against a PR like that as long I was comfortable that the async/await was actually the issue and the improvements were large enough. The reason for the heavy use of the async code is because the main work of this component is the communication over the network to the clients and thus for the most part should be IO bound rather than CPU bound. You may be seeing more CPU bound load depending on how you are testing, for example if you testing is all running locally and IO latency is almost non-existent. 

Also if you are running on a Windows desktop then by default this wont be configured to handle a high throughput of connections (and perhaps you know that already from your mention of the TIME_WAIT issues). You can tune the parameters of Windows to make it support a much higher throughput, see the following;

https://docs.oracle.com/cd/E23095_01/Search.93/ATGSearchAdmin/html/s1207adjustingtcpsettingsforheavyload01.html

Do you have a benchmark/test harness that you can share which simulates this as I am happy to help take a look?

Thanks,
Cain.

**Comment by giantjunkbox** [comment]
Built out some proper tests, and discovered part of the issue, for reasons unknown it takes awhile for things to get going.

I was originally speculating that the the thread pool is relatively slow to add more active threads to the pool. Since it starts out defaulted to the number of hardware threads for both regular worker threads and completion threads, it takes awhile to get the thread pool up to a sufficient size to handle the demand.

Poking around a little bit, I'm not so sure this is the case.

Ignoring that and comparing the synchronous version with the warmed up asynchronous version , the synchronous version still appears to be faster and more efficient, although by a much smaller margin than I originally observed.

On two dedicated VMs, one for sending and the other for receiving. I observe the following:
Asynchronous: 14,000/messages/sec at~80% CPU
Synchronous: 16,000/messages/sec ~65% CPU

The memory usage of the async version does appear to be a few megabytes less memory, so there is that advantage...

I'm also somewhat unsure why I cannot seem to max out the CPUs in either case, this seems like a textbook example of something that SHOULD be able to use every last drop of CPU. I'm wondering if there is some sort of locking occuring in an underlying library. I'm not sure how to go about profiling time spent doing nothing and why. 

The sending side is also somewhat interesting. Using System.Net.Mail to send test messages the performance seems to cap out at about 2,500 messages/sec with anything over a few threads. If I start up multiple processes I can get the message count up to an acceptable rate. Using the async version of .SendMailAsync the CPU usage doubles, maxing out and the rate is slightly slower.

I recall reading somewhere that Microsoft was suggesting folks migrate away from their implementation and onto MailKit as MailKit was way better. I tried that and the performance was completely dismissal.

I keep feeling like I am missing something here, this is the perfect case where async/await SHOULD be way better... 

Minimal Working Example:
https://github.com/giantjunkbox/SmtpServerMinimalWorkingExample

Startup a server, either the SmtpServerReceiver based on the async/await SmtpServer or SmtpServerHackJobReceiver based on SmtpServer with most of the async/await removed. Notably I did as little work as possible to get this working so I could get to the point I could test - obviously a lot of room for improvement.

Once the server is running, startup some clients. For example 30 processes with two threads:
`for /l %f in (1,1,30) do start SmtpFlooder.exe destination.domain.com 2`

At this point, for my project at least, I think the performance is probably fine as is. I'm going to spend some more time trying to understand why it takes awhile to get 'warmed' up. I'll report back if I find anything interesting.

I am however more than a little interested in tracking down the cause or at least understanding what is going on. You clearly put a lot of effort into making this asynchronous for purported performance gains. Not sure that this is time well spent or just a pointless academic exercise.

Thanks and take care

**Comment by giantjunkbox** [comment]
Spent some more time looking at this.

With the async version it can take up to a couple of minutes to get a sufficient number of threads (72) running to handle the requests. Carefully fiddling with the ThreadPool.SetMinThreads appears to improve this; however increasing it to a large value hurts the overall performance. I have been testing with 60 connected clients sending non-stop messages, so 72 threads seems like a sane value. Great!

I'm also curious if the performance benefits of the async model would be more apparent if one had a huge number of mostly idle clients vs a small number of very active clients. As I understand it the whole point is really to minimize context switches and memory overhead of threads. It also seems logical that systems with fewer cores might have a greater benefit. I still find it immensely interesting that the throughput and CPU load is higher on the async version. 

I'm not sure if there is anything actionable to do here... It is probably not worth reworking everything to get a 15% performance improvement and save some CPU cycles - especially given that different use cases could yield radically different results.

**Comment by cosullivan** [comment]
Thanks for your effort on this.

I will take a look at the sample over the next few days as I am also curious to see whether any suitable gains can be made.

Let me know when you have anything you can share for the project you are working on as I am always keen to hear how it is being used.

**Comment by giantjunkbox** [comment]
I was also curious if there were any optimization opportunities, but the profiler is about useless - it just essentially reports almost all of the time is spent on async stuff.... thanks.... Perhaps the new version of Visual Studio does a better job.

The project I am working on is essentially a very fine grained SMTP sink. We have a system that sends pages to via various methods, the system is fairly old and can realistically only process around 50 messages a second - which is generally just fine.

Every once in a while some service or monitor goes nuts and floods us with thousands of messages per second, which subsequently crushes the paging system and causes all sorts of operational issues.

We have made numerous improvements to the system over the years to help minimize these events; however we are at the point where this occurs frequently enough that we really need to be able to precisely pick out offending message at the ingress point and drop them. The idea is that this is essentially a message sink that can absorb the abuse, alert us, and allow us time to go track down and fix the source without impacting operations.

I can half solve this problem 20 different ways, but ultimately nothing really appears to fits cleanly. I was largely dreading having to put together a SMTP server component, very happy I found yours - thanks again.

**Comment by shapemetrics** [comment]
Have you attempted to use an RBL and memory cache model to handle lookups for say 3 or more hours? This could help you reduce the volume of abuse a bit by using spamhaus or some other RBL. I would also look at obrs DNS to see if the IP address is in the list of dynamic/non-static addresses. There are a few other things you can do to attempt find those types of abuses  You can do it at the connection and the possibly add it to the IPSEC or other firewall rule on an edge device to take the load off the server itself

**Comment by giantjunkbox** [comment]
Thanks for the suggestion.

Our use case gets a bit complicated as the 'abuse' originates from internal automated systems and the message flow is often aggregated into a few trusted hosts that end up flooding us on the behalf of the misbehaving systems.

In order to not make things worse we essentially need to have extremely granular control of what gets dropped, while still allowing similar, but slightly different, messages through.

This is not the typical spam problem that there are already tons of great tools for. I have found a number of different generic solutions; however they generally solve part of the problem.

We are fairly far along with this project and it seems to be working as desired, in large part thanks to this very nice SMTP library.
