### ISSUE TITLE
How to extract attachements ?

### ISSUE THREAD

**Issue by AnassKartit** [cosullivan/SmtpServer#105]
How can i extract attachments any example for EML?

**Comment by cosullivan** [comment]
Hi,

The sample here will show you how to read the contents of the message;
https://github.com/cosullivan/SmtpServer/blob/master/Src/SampleApp/SampleMessageStore.cs

The contents if the message will be a MIME document so you can then use something like MimeKit to parse that MIME document and access the attachments.

Thanks,
Cain.
