### ISSUE TITLE
Catching Exceptions for Logging

### ISSUE THREAD

**Issue by jaredrsowers** [cosullivan/SmtpServer#106]
I would like to be able to log all exceptions that happen, but I do not see a way to gain access to them currently.

Am I missing something?

It looks like they only make their way to the Run method of SmtpSession, but die there:
```
public void Run(CancellationToken cancellationToken)
{
    _taskCompletionSource = new TaskCompletionSource<bool>();

    RunAsync(cancellationToken)
        .ContinueWith(t =>  //<-- t.Exception is populated here but it dies here
        {
            try
            {
                // Pass the exception up the chain?
                if (t.Exception != null) 
                {
                    _taskCompletionSource.TrySetException(t.Exception.InnerExceptions);
                }

                _taskCompletionSource.SetResult(t.IsCompleted);
            }
            catch
            {
                _taskCompletionSource.SetResult(false);
            }
        }, 
        cancellationToken);
}
```

By doing this it can be pushed up to SmtpServer.ListenAsync():
```
session.Task
    .ContinueWith(t => //<-- t.Exception is now populated
    {
        if (sessions.TryRemove(session, out var s))
        {
            sessionContext.NetworkClient.Dispose();
        }

        // Maybe add it to the Event Args?
        OnSessionCompleted(new SessionEventArgs(sessionContext, t.Exception));
    },
    cancellationToken);
``` 

While this solution exposes it to the SessionCompleted Event, it will add the Exception property to everywhere that SessionEventArgs is used, and everywhere but here doesn't make sense.

A better solution might be to add a new Event specifically for exceptions, this way there are no breaking changes, or adding properties that don't make complete sense:
```
session.Task
    .ContinueWith(t => //<-- t.Exception is now populated
    {
        if (sessions.TryRemove(session, out var s))
        {
            sessionContext.NetworkClient.Dispose();
        }

        // This might be a better solution with a new event to subscribe to...
        if (t.Exception != null)
        {
            OnSessionError(t.Exception);
        }

        OnSessionCompleted(new SessionEventArgs(sessionContext));
    },
    cancellationToken);
```

What are your thoughts?

**Comment by cosullivan** [comment]
Hi,

Yeah I think that looks fine. 

My preference would be to add the new event as per your last example but calling it SessionFaulted instead. That way the session would either "Fault" or "Complete" but I don't think it should raise the SessionFaulted event and then the SessionCompleted event. 

The SessionFaulted event handler should probably use a SessionFaultedEventArgs which inherits from SessionEventArgs and add's the Exception to it.

Thanks,
Cain.

**Comment by jaredrsowers** [comment]
Sounds good, I will send a pull request.

**Comment by jaredrsowers** [comment]
My only concern with not calling both SessionFaulted  and SessionCompleted is that it would be a somewhat breaking change. In that, if people update their package and have cleanup code that needs to run on the SessionCompleted then it will suddenly stop working until they also implement the cleanup code in SessionFaulted. 

For example, I create a Lifetime Scope for my IOC container in SessionCreated and then I must Dispose it in SessionCompleted. If I were to update my nuget package I would suddenly have a pretty major memory leak.

**Comment by cosullivan** [comment]
Ok, make it raise both the SessionFaulted and SessionCompleted events then.
