### ISSUE TITLE
stream.AuthenticateAsServerAsync never returns

### ISSUE THREAD

**Issue by judebigj** [cosullivan/SmtpServer#108]
Hello ,
           I have set the Secure flag to true and using 587  as secure port.  I am using a self signed wild card certificate. I noticed that with the above settings, i am not able to authenticate as server. It always  gets stuck at AuthenticateAsServerAsync in the NetworkClient.cs.  Please check code below

```
public async Task UpgradeAsync(X509Certificate2 certificate, SslProtocols protocols, CancellationToken cancellationToken = default)
        {
            var stream = new SslStream(_stream, true);
           // Never returns
            await stream.AuthenticateAsServerAsync(certificate, false, protocols, true).ConfigureAwait(false);
            
            _stream = stream;
        }
```

Any Ideas what could be going wrong here?

**Comment by cosullivan** [comment]
Hi,

It's hard to say what could be wrong without being able to run the failing code. How are you calling the server, ie, what mail client are you using?

It could be that the AuthenticateAsServerAsync method is failing if the certificate is not valid, but hard to say without being able to see the certificate.

Another issue might be that the client is failing the negotiating because it cant trust the self signed certificate. If you have a sample (including certificate) that you can send me then I can take a look.

Thanks,
Cain.

**Comment by judebigj** [comment]
*>>How are you calling the server, ie, what mail client are you using?  *
I configured Thunderbird Mail client to send email though the SMTP server
which is running on localhost.
I main objective I am trying to achieve is to mail the SMTP server as a
relay server for GSuite. There is provision
in Gsuite (bussiness Gmail) to forward outgoing emails from a domain to
your SMTP Server
More info here <https://support.google.com/a/answer/2956491?hl=en>

*>>Another issue might be that the client is failing the negotiating
because it cant trust the self signed certificate. If you have a >>sample
(including certificate) that you can send me then I can take a look.*
Attached is a wild card self signed certificate that I am using.

**Comment by cosullivan** [comment]
Hi, there is not attachment?

**Comment by judebigj** [comment]
I had attached the file via email. You can download the certificate file from [here](https://drive.google.com/file/d/1jKu5_G9hANiNbxnwhKFweF1d4gHmqvTR/view?usp=sharing)

**Comment by cosullivan** [comment]
I can't see any issues, I am able to use your certificate in the SecureServerExample and it works fine. 

If you can build the SmtpServer from source and link against that then I would suggest playing around with the boolean parameters of the AuthenticateAsServerAsync method, in particular the last one and see if that makes a difference.

**Comment by judebigj** [comment]
I downloaded the latest source and tried switching the Boolean parameters on and off, but got the same result. To reproduce the issue, I configured Thunderbird to send email smtp server as follows :

![image](https://user-images.githubusercontent.com/9862996/60583410-75ec5580-9da8-11e9-84b5-13f0a8555cc3.png)

I run my application as console app and initialized smtpserver as follows:

```
 SmtpServerOptionsBuilder options = new SmtpServerOptionsBuilder();
options.Endpoint(new EndpointDefinitionBuilder()
options.ServerName(SmtpSetting.Instance.SmtpServerName)
.MessageStore(new EmailHandler())
.MailboxFilter(new GatewayFilter())
.DomainName(SmtpSetting.Instance.WhitelistedDomains)
.Certificate(getX509Certificate());
.Endpoint(builder =>
                    builder
                        .Port(587, true)
                        .AllowUnsecureAuthentication(false));
               
smtpServer = new SmtpServer.SmtpServer(options.Build());
```

Let me know if this helps in reproducing the issue.
I can upload my console app if you want.

**Comment by cosullivan** [comment]
Ok, I see what's going on now.

Your configuration here is not compatible with your Thunderbird settings;

`.Port(587, true)`

It should be

`.Port(587, false)`

That boolean parameter indicates whether or not the endpoint is secure by default, it is the same as doing

`.Port(587).IsSecure(true)`

To use a secure endpoint by default that translates to Thunderbird's "Connection Security: SSL/TLS" option which by default in Thunderbird will be port 465.

If you want to use the STARTTLS mode of connection security (defaulting to port 587) then set this to be false. 

If you want to support both modes you can simply add two endpoints;

```
               .Endpoint(builder =>
                  builder
                        .Port(465, true)
                        .AllowUnsecureAuthentication(false))
                .Endpoint(builder =>
                    builder
                        .Port(587, false)
                        .AllowUnsecureAuthentication(false))
```
Thanks, 
Cain.

**Comment by judebigj** [comment]
Hello Cain,
                 Its working now! Thanks for that.
I have another scenario where the Authentication gets stuck:
Gsuite\Gmail has option to relay outgoing emails to an outbound SMTP server. You can find more info
[here](https://support.google.com/a/answer/178333?hl=en).
Our SMTP server is running on port 8888 

```
options.ServerName(SmtpSetting.Instance.SmtpServerName)
                .MessageStore(new EmailHandler())
                .MailboxFilter(new GatewayFilter())
                .DomainName(SmtpSetting.Instance.WhitelistedDomains)
                .Certificate(getX509Certificate())
                .Endpoint(builder =>
                  builder
                        .Port(8888, true) 
                        .AllowUnsecureAuthentication(false))
```

In this scenario too the AuthenticateAsServerAsync  never returns. I assume this could be because of
the self signed certificate I am using. You thoughts?

**Comment by cosullivan** [comment]
Hi,

When you configured your Outbound Gateway Route? There are 3 options according to that link, _Perform MX lookup on host_, _Require secure transport (TLS)_, and _Require CA signed certificate_.

I haven't dealt with this before but I would suspect that if you have the 3rd option enabled then your self signed certificate wont work as it's not been signed but a trusted root. That might also be the case with option 2 however given that option 3 is more specific around a CA signed certificate then perhaps option 2 doesn't validate the issuer of the certificate. 

Also its interesting that the AuthenticateAsServerAsync hangs as opposes to throws an exception. Are you running this on Windows or Linux?

Thanks,
Cain.

**Comment by judebigj** [comment]
I just have the 2nd option checked (CA signed Cert is not checked). I am
running this on Windows Server.

>> Also its interesting that the AuthenticateAsServerAsync hangs as opposes
to throws an exception.
Well, it eventually does after a while, this what I get :

Session Faulted!!
System.IO.IOException: Unable to read data from the transport connection: A
connection attempt failed because the connected party did not properly
respond after a period of time, or established connection failed because
connected host has failed to respond. --->
System.Net.Sockets.SocketException: A connection attempt failed because the
connected party did not properly respond after a period of time, or
established connection failed because connected host has failed to respond
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset,
Int32 size)
   --- End of inner exception stack trace ---
   at
System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult
lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult
result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult
iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean
requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
   at
System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at SmtpServer.IO.NetworkClient.<UpgradeAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
   at
System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at SmtpServer.SmtpServer.<ListenAsync>d__16.MoveNext()
