### ISSUE TITLE
change IP address of smtp server

### ISSUE THREAD

**Issue by sekmenhuseyin** [cosullivan/SmtpServer#109]
Hi,

We have a problem that we couldn't solve on our own. We use Azure VM for smtp server. Its private IP is 10.0.0.4 and public IP is 20.188.39.114. When we send emails, smtp server uses private IP and because of that reciver servers can not find real domain name.

`Nevertheless your message appears to be sent from !10.0.0.4!.`
`You may want to publish a DNS record (A type) for the hostname !10.0.0.4! or use a different hostname in your mail software.`
https://mxtoolbox.com/deliverability/f7170504-3af2-4a46-aa5c-2069780a37a8

How can I configure smtp server to use real IP.

**Comment by cosullivan** [comment]
Hi,

I don't really understand what your issue is.

When you say "When we send emails, smtp server uses private IP" how are you sending the emails? The SmtpServer component will only receive emails.

Thanks,
Cain.

**Comment by sekmenhuseyin** [comment]
Sorry, my mistake. I really thought we were sending emails with smtp server.
