### ISSUE TITLE
Send email using my SMTP Server

### ISSUE THREAD

**Issue by nsabbagh** [cosullivan/SmtpServer#114]
Hi, I tried to send an email using my SMTP Server to any gmail account, but couldn't.
I'm using this code

```
            MailMessage mailMessage = new MailMessage();
            mailMessage.From = new MailAddress("test@test.com");
            mailMessage.To.Add("nour.alsabbagh1@gmail.com");
            mailMessage.Subject = "subject";

            mailMessage.Body = "body";
            mailMessage.IsBodyHtml = true;

            SmtpClient smtpClient = new SmtpClient("localhost", 25);
            smtpClient.UseDefaultCredentials = true;
            smtpClient.Send(mailMessage);
```

The listener is receiving the message and is handeling it. 

![image](https://user-images.githubusercontent.com/57805703/68956949-c2718400-07d1-11ea-9829-eff07571defd.png)

But unfortunately the gmail account is not receiving the message.
Did I use it wrongly?

**Comment by ml-workshare** [comment]
Try sending mail to a disposable email address (eg. sharklasers.com). It's possible it's being eaten by a spam filter.

**Comment by nsabbagh** [comment]
Actualy, I'm using this app (cosullivan/SmtpServer) on two server, one on Amazon and the second is on my machine. What I'm trying to do is to send the an email using my local app (cosullivan/SmtpServer) to the app (cosullivan/SmtpServer) which is hosted on the Amazon server, also it dosent dilver it. But I will try to use sharklasers email and get back to you.

**Comment by ml-workshare** [comment]
I'd also consider networking issues. Maybe some hints here to check connectivity. https://docs.microsoft.com/en-us/exchange/mail-flow/test-smtp-with-telnet?view=exchserver-2019

**Comment by nsabbagh** [comment]
Also didn't work! I'm using a very easy straight forward code, have you tried to send an email using this app before? 


            MailMessage mailMessage = new MailMessage();
            mailMessage.From = new MailAddress("test@test.com");
            //mailMessage.To.Add("test1@ec2-3-231-141-207.compute-1.amazonaws.com");
            mailMessage.To.Add("nour.alsabbagh@sharklasers.com"); 
            mailMessage.Subject = "subject";

            mailMessage.Body = "body";
            mailMessage.IsBodyHtml = true;

            SmtpClient smtpClient = new SmtpClient("localhost", 25);
            smtpClient.UseDefaultCredentials = true;
            smtpClient.Send(mailMessage);

**Comment by nsabbagh** [comment]
Also didn't work! I'm using a very easy straight forward code, have you tried to send an email using this app before?

        MailMessage mailMessage = new MailMessage();
        mailMessage.From = new MailAddress("test@test.com");

        mailMessage.To.Add("nour.alsabbagh@sharklasers.com"); 
        mailMessage.Subject = "subject";

        mailMessage.Body = "body";
        mailMessage.IsBodyHtml = true;

        SmtpClient smtpClient = new SmtpClient("localhost", 25);
        smtpClient.UseDefaultCredentials = true;
        smtpClient.Send(mailMessage);

**Comment by ml-workshare** [comment]
Yes, I've used it successfully in production qa.

I just re-read your code. You're using mimekit/mailkit to send email to localhost, which I assume is using this smtp library. All this library does is receive email. It doesn't onforward it for you - you have to write that bit yourself. 

See: https://github.com/cosullivan/SmtpServer/issues/95

**Comment by nsabbagh** [comment]
Actually yes, I'm trying to send email but NOT to localhost, I'm connecting to (cosullivan/SmtpServer) which is already running on my localhost machine and let (cosullivan/SmtpServer) to send me email to the appropriate email address

**Comment by ml-workshare** [comment]
All this library does is receive email. It doesn't onforward it for you. You can extend this library to do that for you.

See also: https://github.com/cosullivan/SmtpServer/issues/89

**Comment by nsabbagh** [comment]
Alright, Thank you so much
