### ISSUE TITLE
The SMTP server does not support authentication.

### ISSUE THREAD

**Issue by justinjstark** [cosullivan/SmtpServer#115]
I just upped SmtpServer from 5.4 to 6.3. Now I get this when authenticating using MailKit.MailService.Authenticate.

`System.NotSupportedException: 'The SMTP server does not support authentication.'`

Below is the code I'm using to construct the server. In 5.4, I used this exact same configuration but with the old SmtpOptionsBuilder methods for AuthenticationRequired and AllowUnsecureAuthentication.

```csharp
            var options = new SmtpServerOptionsBuilder()
                .ServerName("localhost")
                .Port(25, 587)
                .UserAuthenticator(userAuthenticator)
                .Endpoint(b => {
                    b.AuthenticationRequired(false);                    
                    b.AllowUnsecureAuthentication(true);
                })
                .MessageStore(new MiddlewareMessageStore(stack, logger))
                .Logger(new SmtpLoggerWrapper(logger))
                .Build();

            _smtpServer = new SmtpServer.SmtpServer(options);
```

**Comment by justinjstark** [comment]
Also, I don't know if it matters, but I'm trying to auth with a blank password.

**Comment by justinjstark** [comment]
Here is my user authenticator:

```csharp
            var userAuthenticator = new DelegatingUserAuthenticator((s, u, p) => {
                s.Properties["SmtpUsername"] = u;
                return true;
            });
```

**Comment by cosullivan** [comment]
Hi @justinjstark ,

I think the issue is that you are calling .Port(...) and .Endpoint(...) together.

This was a change in that the .Port(...) is just a wrapper around defining a default endpoint for each of those ports that you have supplied. In your case, it's creating 3 endpoints, and your third endpoint wont be used as it doesn't have a port.

Can you try this?

```
        var options = new SmtpServerOptionsBuilder()
                .ServerName("localhost")
                .UserAuthenticator(userAuthenticator)
                .Endpoint(b => {
                    b.Port(25); // or 587
                    b.AuthenticationRequired(false);                    
                    b.AllowUnsecureAuthentication(true);
                })
                .MessageStore(new MiddlewareMessageStore(stack, logger))
                .Logger(new SmtpLoggerWrapper(logger))
                .Build();

            _smtpServer = new SmtpServer.SmtpServer(options);
```

**Comment by justinjstark** [comment]
That was it. Thank you.
