### ISSUE TITLE
SmtpServer can only be used with .Net Framework 2.0, nothing later - is that correct?

### ISSUE THREAD

**Issue by PaulCutcliffe** [cosullivan/SmtpServer#116]
**Hi!**

I have been working on an application that will run alongside a bespoke application that sends mail notifications via SMTP but doesn't support SSL or TLS connections. It will receive SMTP mail from this other application, then relay it to an SMTP server that insists on secure connections, such as those of Gmail, for example. 

I've started with an [open-source project](https://www.codeproject.com/Articles/456380/A-Csharp-SMTP-server-receiver) that simply receives SMTP mail and simply stores it to disk, and I'm working on modifying it to relay the mail. 

I've just found your SmtpServer project and am interested to see if using it might be less work and yield better results. However, the other project uses the .NET Framework 4 Client Profile, and [the SmtpServer NuGet package](https://www.nuget.org/packages/SmtpServer/) says it's not compatible and can only use the .NET Framework 2.0 - is that correct? Assuming it is, are there any plans to update it so it can use the later framework?

It may turn out to be better to start from scratch using this component anyway - not a massive deal as it's quite a new project, but I'm also quite new to C# and have only ever used the later frameworks, at least, so far. 

Thanks,

**Paul Cutcliffe** 
🎅Merry Christmas!🎄

**Comment by cosullivan** [comment]
Hi @PaulCutcliffe ,

It's built against .NET Standard 2.0 (which is different from .NET Framework 2.0) so it will run on .NET Framework 4.6.1+ and .NET Core 2.0+.

See here for the version compatibility table;
https://github.com/dotnet/standard/blob/master/docs/versions.md

Thanks,
Cain.

**Comment by PaulCutcliffe** [comment]
Ah, that's great, and thanks for clarifying. 😁
