### ISSUE TITLE
IP Address of outgoing mail

### ISSUE THREAD

**Issue by Fleischhauer** [cosullivan/SmtpServer#117]
Can you change/set the ip-address of outgoing mail to bypass SPF?

**Comment by cosullivan** [comment]
Hi,

I'm not really sure what you mean here? This component is just the server component so it doesn't send emails?

Thanks, Cain.

**Comment by Fleischhauer** [comment]
Well, sorry. I'm not that into packets yet. But the server has to send outgoing mails somehow, no? I want to spoof the out-ip of those packets.

**Comment by cosullivan** [comment]
Hi,

No, this will not send the emails for you. 

It is a component that handles the communication with Mail clients and Mail transfer agents and then will pass the incoming email onto your custom implementation of an IMessageStore.

If you want a full mail server then you can build one using this component, but it is not a full mail server.

Thanks, Cain.

**Comment by Fleischhauer** [comment]
Oh, that was a misconception on my part.
In the example you use MailKit to actually send the mail? Is that from MimeKit?
Could you recommend a server that can do that?

**Comment by reinaldocoelho** [comment]
To send emails you can use an simple postfix and paste to that the EML to send.

I was have this doubt in the past. :-D
We use SmtpServer to receive and a connection to postfix to send e-mails :-)

**Comment by Fleischhauer** [comment]
I see, thank you!

I guess I'll just search for something that can send custom packets then.
