### ISSUE TITLE
TLS not working after upgrading to .Net Core 3.1

### ISSUE THREAD

**Issue by kurucz09** [cosullivan/SmtpServer#119]
Hi,

We have been using the SmtpServer component for more then one year. Our product runs in a docker container and receives email from Microsoft Exchange, updates the signature and then sends it back. The email from exchange to the component is sent through an outbound connector using TLS1.2 with a self signed certificate. After upgrading from .Net Core 2.2 to .Net Core 3.1 this stopped working. If we disable the need for TLS then the mail flow works correctly. Any idea what could have cause this?
Note: Upgrading to the latest version does not solve the problem.

**Comment by cosullivan** [comment]
Hi @kurucz09,

I'm not sure what the issue would be but my guess is that it might be related to this change in .NET Core 3.0;
https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-3-0#tls-13--openssl-111-on-linux

What's not clear from that link though is whether TLS1.3 is forced when running on Linux. 
If you are running on Docker then you are obviously running on Linux and then I assume the Exchange server would be running on Windows and in which case Windows doesn't support 1.3.

It might be worthwhile investigating this angle.

Thanks,
Cain.

**Comment by AndriyTemplafy** [comment]
Hi @cosullivan 

When we tried to run it on Docker, it didn't connect to Windows Exchange server even though the following setting was Tls12
```
SmtpServerOptionsBuilder smtpServerOptionsBuilder = new SmtpServerOptionsBuilder()
                ...
                .SupportedSslProtocols(SslProtocols.Tls12)
```

So yes, it looks like on Linux using Tls1.3 is somehow forced. When we run the server on Windows it works with Tls12 setting, but stops working if we change it to Tls13 setting, as expected.  
 
Best regards,
Andriy
