### ISSUE TITLE
Listener stops after a while

### ISSUE THREAD

**Issue by gurc4n** [cosullivan/SmtpServer#123]
Hi,
I am trying to develop a really simple app, it just needs to listen on port 25 and write to a database.

I created the server just like in the sample server app.

It works for several messages.. and stops listening..

Do I need to trigger the cancellation token after every message and recreate the server? Or do I miss something else here?

**Comment by cosullivan** [comment]
Hi @gurc4n ,

No, the server doesn't need to be stopped, it should just keep running. When you say it stops listening, does it stop accepting new connections? 

How many connections does it make before it stops and what operating system are you running?

Thanks, Cain.
