### ISSUE TITLE
IP address of remote endpoint is not working in filter in version 6.4.0+

### ISSUE THREAD

**Issue by AndriyTemplafy** [cosullivan/SmtpServer#127]
Hi,

We use this code to validate the IP address of the sender. In version 5.3.0 where there is still a property `context.RemoteEndPoint`, it works and we get a valid sender IP address. But in the following code, that we tested in all versions 6.4.0, 6.5.0, 7.0.0, it always returns IP 0.0.0.0

```csharp
public class ClientIpMailboxFilter : MailboxFilter
    {

        public override async Task<MailboxFilterResult> CanAcceptFromAsync(ISessionContext context, IMailbox from, int size, CancellationToken cancellationToken)
        {
            var remoteIpEndPoint = context.EndpointDefinition.Endpoint;
            if (ranges.Any(ip => ip.Contains(remoteIpEndPoint.Address)))
            {
               ...valid IP
            }
            else {
               ...invalid ip
            }
        }
    }
```

**Comment by cosullivan** [comment]
Hi @AndriyTemplafy ,

Please see the following sample as to how it can be done now.
https://github.com/cosullivan/SmtpServer/blob/master/Src/SampleApp/SampleMailboxFilter.cs#L32

Thanks, Cain.

**Comment by AndriyTemplafy** [comment]
Thank you! This worked.
