### ISSUE TITLE
Update SampleMailboxFilter - cannot put required params after optional ones

### ISSUE THREAD

**Issue by cdwiegand** [cosullivan/SmtpServer#130]
```
public class SampleMailboxFilter : IMailboxFilter, IMailboxFilterFactory
{
    public Task<MailboxFilterResult> CanAcceptFromAsync(ISessionContext context, IMailbox @from, int size = 0, CancellationToken token)
    { 
```

causes an Error CS1737: Optional parameters must appear after all required parameters - I believe size should not have `=0` after it.

**Comment by cosullivan** [comment]
Hi @cdwiegand,

I assume this was from the Readme file that you found this. 

I have updated that now.

Thanks, Cain.
