### ISSUE TITLE
[Feature Request] IMAP Server Interface

### ISSUE THREAD

**Issue by jmacato** [cosullivan/SmtpServer#133]
Hi! This library is quite cool btw! I don't know if this is still within the scope of this project but i think it'd be beneficial for it to have a IMAP server so that users can use this as their primary mail server and use clients like Thunderbird.

I know it'd be quite a trouble to implement but I'd like to hear your thoughts about this. Thanks and have a good day :)

**Comment by cosullivan** [comment]
Hi, thanks for your feedback.

I don't think the IMAP server fits into this project. 

With a mail server, there are really two parts to it, the SMTP server that deals within the incoming messages and then the IMAP (and/or POP3) server that deals with the interactions for the message clients. I feel they are two distinct projects as opposed to one.

Thanks, Cain.

**Comment by jmacato** [comment]
I see.. too bad.. I cant find any c# based solution for IMAP... ohwell... if you know anything in that direction it'd be quite helpful! and thanks for the response :)

**Comment by large** [comment]
@jmacato my best bet for what you are looking for: https://github.com/hmailserver/hmailserver

Please note that it is C++ with COM references that are adaptable to C#
I have been running a hMailserver since 2007 so it is stable.

Now I have my own spam proxy using this smtpserver between with great success.

**Comment by jmacato** [comment]
@large thanks for the link but i'm looking for a fully managed/c# based one since i really really dont like native binaries...

**Comment by markjerz** [comment]
@jmacato did you manage to find something for this?

**Comment by jmacato** [comment]
@markjerz sadly not... i was not able to use this library in any capacity.. lack of docs and good examples prevented me from doing so.
