### ISSUE TITLE
SmtpServerOptionsBuilder.MaxMessages

### ISSUE THREAD

**Issue by reponemec** [cosullivan/SmtpServer#137]
Is it possible to limit the maximum number of messages server receive? Per a time period (or session) and domain.

**Comment by cosullivan** [comment]
Hi @reponemec,

You can implement this logic yourself within a IMailboxFilter implementation.
https://github.com/cosullivan/SmtpServer/blob/master/Src/SmtpServer/Storage/IMailboxFilter.cs#L17

You can either return a MailboxFilterResult or throw a SmtpResponseException from within this filter to return a more specific response back to the client.

Thanks, Cain.
