### ISSUE TITLE
SpamAssassin integration 

### ISSUE THREAD

**Issue by panterlo** [cosullivan/SmtpServer#14]
This is a great project, thanks sharing ! Anyway have you thought about a SpamAssassin integration (over TCP) or to you rather think it's better to put a Postfix + Amavisd in front of this C# SmtpServer to handle filtering ?

We are looking at using it to provider inbound e-mail web hooks (we are aware that there are SendGrid, Mailgun that provides inbound web hooks but we prefer to run it closer "to our infrastructure").

**Comment by cosullivan** [comment]
Hi, I am glad you like it.

I did look briefly into SpamAssassin a while back, but ended up using a Bayesian filter internally from the app. The Bayesian filter was implemented using a commercial product written in C# so it made things a lot easier. This didn't go into a production environment though, but from the tests I did it worked really well. 

I implemented this by putting it into the IMessageStore interface which gets called when the message has been successfully received from the sender.

Personally, I think it would be better to hook into the SpamAssassin API from within the IMessageStore interface but I am also not familiar with Amavisd so can't really comment on that.

It's a shame that Google don't expose a have a Spam API (not one that I know of anyway) as that would be a perfect fit.
