### ISSUE TITLE
Best hosting environment

### ISSUE THREAD

**Issue by reponemec** [cosullivan/SmtpServer#142]
I'm looking for a best hosting environment for your SmtpServer library. All your examples are using just a simple console application. 
Is .Net Core console application the best solution for hosting SmtpServer on production Windows or CentOS servers?

**Comment by cosullivan** [comment]
Hi,

Console App's are easy to get running which I why I have created the samples like that. However, there is no real best practice on how you would host the SmtpServer. 

It could be a Console App, a Windows Service, an ASPNET Core app, it really doesn't matter. 

Thanks, Cain.
