### ISSUE TITLE
MessageStore breaking changes?

### ISSUE THREAD

**Issue by reponemec** [cosullivan/SmtpServer#143]
It looks SmtpServerOptionsBuilder.MessageStore operation has been completely rewrited since 8.0.1 version of SmtpServer. 

Old:
`new SmtpServerOptionsBuilder().MessageStore(new SampleMessageStore());`

New:
`serviceProvider.Add(new SampleMessageStore());`

Seems significant breaking changes comparing with 7.0.2. Is there any updated readme.md about "How can it be used?"
And which version of package you recommend me should I use? I experimented with 7.0.2 for a long time, but it looks its startup API will be replaced with the new one.

**Comment by cosullivan** [comment]
Hi,

Yes, version 8 does contain some breaking changes mostly around performance, but also around improving extensibility. I am still working through this document which will describe the changes and hope to have that complete in the next week or two.
https://github.com/cosullivan/SmtpServer/blob/master/Version8.md

If you need to reference how the changes work, all of the sample where applicable have been updated.

The SmtpServerOptionsBuilder is now specifically just for the options, whereas the services such as IMessageStore, IMailboxFilter, IUserAuthenticator are now supplied via the IServiceProvider which works better for Dependency Injection, see here for an example;
https://github.com/cosullivan/SmtpServer/blob/master/Examples/WorkerService/Program.cs

Thanks, Cain.

**Comment by reponemec** [comment]
OK, thanks.

**Comment by cosullivan** [comment]
I've updated the doco here;
https://github.com/cosullivan/SmtpServer/blob/master/Version8.md
