### ISSUE TITLE
NuGet package v8.0.1

### ISSUE THREAD

**Issue by sandord** [cosullivan/SmtpServer#144]
I saw the v8.0.1 version show up on NuGet and I upgraded my package references. 

I got more than a few breaking changes but I can't seem to find any upgrade hints. When checking this GitHub page, I was that the latest release is supposed to be 7.2.0. 

I tried sifting through the commit messages but I got the feeling that development is still in progress.

I guess I should stick with 7.2.0 for now (which works fine for me).

**Comment by cosullivan** [comment]
Hi @sandord,

Yes, v8 does have breaking changes and the documentation is still a work in progress. I hope to have the upgrade notes available soon.

See this for additional information too;
https://github.com/cosullivan/SmtpServer/issues/143#issuecomment-720180570

Thanks, Cain.

**Comment by cosullivan** [comment]
I've updated the doco here;
https://github.com/cosullivan/SmtpServer/blob/master/Version8.md

**Comment by sandord** [comment]
Thanks a lot! This provided me with enough information to complete the upgrade.
