### ISSUE TITLE
TLS broken in version 8

### ISSUE THREAD

**Issue by nopap** [cosullivan/SmtpServer#145]
Hi, 
I think TLS is broken in version 8, i'm not able to handshake when IsSecure=true. Either with openssl s_client or from a C# piece of code or MailKit like in your sample.
Same server code with SmtpServer version 7 works fine, handshake ok.

Or i'm missing something like a new option to set somewhere.

Thanks

**Comment by cosullivan** [comment]
Hi @nopap ,

Thanks for picking that up. I didn't actually have a unit test for that scenario so it slipped through the cracks when I was refactoring. 

I have fixed this and pushed a new package version 8.0.3 to NuGet which should be available shortly.

Thanks, Cain.

**Comment by nopap** [comment]
All tested ok. Thanks.
