### ISSUE TITLE
What sender address when use SmtpClient?

### ISSUE THREAD

**Issue by ahdung** [cosullivan/SmtpServer#158]
This is maybe a stupid question, forgive me please.

I use this started a server:
```c#
var options = new SmtpServerOptionsBuilder()
    .ServerName("localhost")
    .Port(25, 587)
    .Build();

var smtpServer = new SmtpServer.SmtpServer(options, ServiceProvider.Default);
await smtpServer.StartAsync(CancellationToken.None);
```
so how to set the sender address in SmtpClient?

**Comment by cosullivan** [comment]
Hi, this component is actually an SMTP Server, not an SMTP Client so you may be looking in the wrong place.

If you want an SMTP Client, check out https://github.com/jstedfast/MailKit

**Comment by ahdung** [comment]
I know this is a server, my question is when use client connect the server, what address I should type?

**Comment by cosullivan** [comment]
When you say the "sender address" are you referring to the sender's address of the email itself, or the address of the server you want to connect to?

If you are referring to the address of the server, then you would use the Smtp Client and connect to the IP address of the host machine that the SMTP Server is running on,.

If you are referring to the sender's address on the email, then that's irrelevant from the perspective of the SMTP server component.

Perhaps share more code to show what you are doing?

**Comment by ahdung** [comment]
Sorry my English is not good.
Actually my purpose is send mail without provider account, so I want integrate a SMTP server into my app, and send mail to users by the App self, without using gmail/outlook or other else, so when I started a `SmtpServer`, how to send mail directly? Thank you.

**Comment by cosullivan** [comment]
Ok, I don't think this will suit your needs. This SMTP Server wont act as a relay server which is what you need by the sounds of it.

This is just designed to handle the communications with a Mail Client.

**Comment by ahdung** [comment]
Do you mean this server can't really send a mail to someone?

**Comment by cosullivan** [comment]
Yes, that is correct.

**Comment by ahdung** [comment]
I see. so~let me curious to ask, what does it do?

**Comment by ahdung** [comment]
I think I got it, it can be a message receiver, accept message in, but never process out. right?

**Comment by cosullivan** [comment]
yes that is correct.

If you wanted to forward the message you would need to handle that yourself.
