### ISSUE TITLE
SmtpServer.StartAsync blocks when called in .NET5

### ISSUE THREAD

**Issue by everttimmer1963** [cosullivan/SmtpServer#159]
I am porting an existing SmtpService (.net framework windows service) using SmtpServer to .NET5 and I am running into a problem.

Upon starting the service, StartAsync blocks and never returns. For debugging, I changed the configuration to the minimal possible configuration before starting the service, so effectively, the code results into this:

`var options = new SmtpServerOptionsBuilder()
    .ServerName("localhost")
    .Port(25, 587)
    .Build();

var serviceProvider = ServiceProvider.Default;
SmtpServer server = new SmtpServer(options, serviceProvider);

await server.StartAsync(CancellationToken.None);`

**Comment by everttimmer1963** [comment]
A non-issue. I was under the assumption that StartAsync would be a non-blocking call but that does not seem to be the case. The server now accepts and receives emails without any problem,

**Comment by jlrouzies-mantu** [comment]
Hey, I'm encountering the same issue, I can start the .exe from PowerShell no problem, but from a Windows service and it just timeout the start, like it never release / returns, so the service does not start

Edit: nvm, my .NET 8.0 host didn't have the UseWindowsService
