### ISSUE TITLE
Please push 2.0.0-Beta1 to nuget.org

### ISSUE THREAD

**Issue by mrinc** [cosullivan/SmtpServer#16]
Hello,

Please could you push v2.0.0-Beta1 to nuget.org as its the current version in master?

In future, could a branching structure of develop/master be used so master is always the latest stable and develop being the awesome new stuff or something like this?

Thanks

**Comment by mrinc** [comment]
Never mind, I thought the 'include prereleases' checkbox was checked :D

**Comment by cosullivan** [comment]
No worries.

 

I also forgot to push the change to the project.json that contained the update version number.

 

Thanks,

Cain
