### ISSUE TITLE
BDAT command support

### ISSUE THREAD

**Issue by reinaldocoelho** [cosullivan/SmtpServer#179]
Hello Cain!

In #34 you say that you are developing a BDAT command support for the library.

Has this feature been realized?

**Comment by cosullivan** [comment]
Hi @reinaldocoelho ,

I did some refactoring a while back to make this easier to support, but never ended up implementing it due to it not widely being used.

Thanks, Cain.

**Comment by reinaldocoelho** [comment]
Thank you @cosullivan !!
