### ISSUE TITLE
Bug on receive data broke special chars.

### ISSUE THREAD

**Issue by reinaldocoelho** [cosullivan/SmtpServer#18]
When SmtpServer receive EML with special chars, lib broke chars and chage that to "?" instead.
Characteres are broked in Subject and Body.

How to reproduce:

1. Steps
    1. Run SmtpServer
    1. Open console.
    1. Insert command: telnet 127.0.0.1 25 (suposing you are using 25 port)
    1. Follow commands in [smtp-telnet-commands.txt](https://github.com/cosullivan/SmtpServer/files/850515/smtp-telnet-commands.txt)
1. Expected
    1. Special chars in Subject are received OK.
    1. Special chars in Body are received OK.
1. Received
    1. Special chars in Subject are replaced by "?"
    1. Special chars in Body are replaced by "?"

Attach, follow the EML file to test.

[content-transfer-encode-8bit.zip](https://github.com/cosullivan/SmtpServer/files/850501/content-transfer-encode-8bit.zip)

**Comment by reinaldocoelho** [comment]
C# code to reproduce the same error, the e-mail was received with special char broken:

            var message = new MailMessage("test@gmail.com", "receiveaccount@test.com")
            {
                Subject = "Subject test çãõáéíóú",
                IsBodyHtml = false,
                Body = null
            };
            using (AlternateView body = AlternateView.CreateAlternateViewFromString(
                    "Body special char çãõáéíóú",
                    message.BodyEncoding,
                    message.IsBodyHtml ? "text/html" : null))
            {
                message.SubjectEncoding = System.Text.Encoding.UTF7;
                body.TransferEncoding = TransferEncoding.EightBit;
                message.AlternateViews.Add(body);
                try
                {
                    using (var smtp = new System.Net.Mail.SmtpClient("127.0.0.1", 9025))
                    {
                        smtp.EnableSsl = false;
                        smtp.Send(message);
                    }
                    Console.WriteLine("Sent with success.");
                }
                catch (SmtpException ex)
                {
                    Console.WriteLine("Error on sent. Ex:" + ex.Message);
                    System.Diagnostics.Debug.WriteLine(
                        ex.Message);
                }
            }

**Comment by cosullivan** [comment]
Thanks for raising that. I think this comes down to me needing to implement the 8BITMIME extension such that the UTF8 can be advertised to the client and then used. At the moment, everything is just using the ASCII encoding (but the 8BITMIME extension allows the body to be extended).

I will do this over the coming few days.

**Comment by reinaldocoelho** [comment]
infelizmente

Hi @cosullivan.

I created a branch to try to solve the problem changing ASCII encoding to UTF8, but  not worked.
I changed the file NetworkTextStream.cs and fixed UTF8 in tests, but unfortunately not work :-(

I don´t know if help, but the commit is in here:
https://github.com/reinaldocoelho/SmtpServer/tree/eight-bit-mime

I tried to follow the RFC6152 (https://tools.ietf.org/html/rfc6152).

**Comment by cosullivan** [comment]
Hi @reinaldocoelho, thanks for putting in the time for the initial investigation. I've been looking at this too and there are a few issues;

Firstly, there was a bug in the parser when it was looking for the ESMTP MAIL parameters which I have now fixed. Do a diff on the the SmtpCommandFactory.cs file on my branch;
https://github.com/cosullivan/SmtpServer/tree/feature/8bitmime

The second issue is the mail client. What should happen is that the Mail Server sends the 8BITMIME option during the EHLO command sequence which informs the mail client that 8BITMIME is available. Then, when the mail client sends the MAIL FROM command, it also includes an optional BODY=8BITMIME parameter. These parameters should be passed through to the parameters dictionary in the constructor of the MailCommand. The bug that I mentioned above was stopping this dictionary from being populated correctly. This now works, but I'm not sure how to get the mail client to actually send this additional parameter. From looking through the source, it looks like you need to set the International format option before the SmtpClient will recognize it, however, I've tried that and still dont see the command come through. 

I will continue to look over the next few days, but at least this should give you a helping hand too.

Thanks,
Cain

**Comment by cosullivan** [comment]
Hi @reinaldocoelho,

I've pushed an updated to this feature branch;
https://github.com/cosullivan/SmtpServer/tree/feature/8bitmime

and it looks as though it is now working. 

I will upload the package to Nuget over the next week when I am certain it is working.

Thanks,
Cain

**Comment by reinaldocoelho** [comment]
Hi @cosullivan .

I will test the changes :-)

Thank you very mutch,
Reinaldo.

**Comment by reinaldocoelho** [comment]
Hi @cosullivan.

I created a simple project to send 8bit mime e-mails with System.Net.Mail.SmtpClient.
The code is in here: https://github.com/reinaldocoelho/Send8BitEmailExample

Unfortunately when the SmtpServer receive this call, the body broke special chars.

I´m not understand the problem yet, but when I sent the destination to my gmail account, the special charrs looks fine.

Thanks again.
Reinaldo.

**Comment by cosullivan** [comment]
Hi @reinaldocoelho,

It looks as though the System.Net.Mail.SmtpClient will only send the BODY=8BITMIME when the SmtpDeliveryFormat is set to International;
https://msdn.microsoft.com/en-us/library/system.net.mail.smtpdeliveryformat(v=vs.110).aspx

I'm not sure whether it would present any issues if the message data was always read as UTF8, I will have to test this out, but according to the RFC, the message client should send the BODY=8BITMIME to enable UTC 8 for the message. There are some other RFC extensions that allow for unicode to be used in the email addresses, but 8BITMIME should cover the body.

It might be that Gmail is actually reading the message headers on the email and extracting the Content-Transfer-Encoding message header that would come through before the actual message content and it could be acting upon that.

I will have another look into this.

Thanks,
Cain

**Comment by reinaldocoelho** [comment]
Hi @cosullivan.

In the example I defined SmtpDeliveryFormat to International, but not work.

I readed in some place about use UTF8 as a default reader encode, because UTF8 read all ASCII chars plus special chars over cost of space and memory usage because of aditional bit.

If I can help, I will be happy :-)

Thanks.

**Comment by cosullivan** [comment]
Ok, I would say that Gmail probably looks at the Content-Transfer-Encoding message header and automatically uses UTF8. 

Postfix does this as well;
http://www.postfix.org/postconf.5.html
detect_8bit_encoding_header

I will add support for automatic detection.

**Comment by reinaldocoelho** [comment]
Cool.

Thanks.

**Comment by reinaldocoelho** [comment]
@cosullivan Can I try to develop this support for automatic detection?

I would like to know if you have any proposal on implementing this solution, at least so that I follow the path most appropriate for the library?

Thanks.

**Comment by cosullivan** [comment]
In looking at this, I think this actually might be more of an issue with the SmtpClient. I am using the MailKit SmtpClient and everything looks to be handled correctly.

Take the following as an example;

    var message = new MimeKit.MimeMessage();
    message.From.Add(new MimeKit.MailboxAddress($"{name}{counter}@test.com"));
    message.To.Add(new MimeKit.MailboxAddress("sample@test.com"));
    message.Subject = $"Subject test çãõáéíóú";

    message.Body = new TextPart(TextFormat.Plain)
    {
        Text = "Test Message Body special char çãõáéíóú",
    };

When I disable the 8BITMIME extension, that is sent through as follows;

    From: SmtpServer.Mail.Mailbox (127.0.0.1:23597)
    To: sample@test.com
    From: A1@test.com
    Date: Sat, 29 Apr 2017 12:32:52 +0800
    Subject: A 1 Subject test =?iso-8859-1?b?5+P14ent8/o=?=
    Message-Id: <MMOSWPP761U4.934PMW6JKM4B2@Cains-Surface-4>
    To: sample@test.com
    MIME-Version: 1.0
    Content-Type: text/plain; charset=utf-8
    Content-Transfer-Encoding: base64
    
    VGVzdCBNZXNzYWdlIEJvZHkgc3BlY2lhbCBjaGFyIMOnw6PDtcOhw6nDrcOzw7o=

And correctly, the message body has been base64 encoded and the subject line has been encoding in quoted-printable.

If I then load that message content using the MimeKit parser;

    var message = MimeKit.MimeMessage.Load(new MemoryStream(Encoding.ASCII.GetBytes(MIME)));
    Console.WriteLine(message.Subject);
    Console.WriteLine(message.TextBody);

I get the following;

    A 1 Subject test çãõáéíóú
    Test Message Body special char çãõáéíóú

So the MimeKit parser has correctly decoded those values as required.

Then, if I turn on the 8BITMIME extension and try again, I get the following;

    From: SmtpServer.Mail.Mailbox (127.0.0.1:23670)
    To: sample@test.com
    From: A1@test.com
    Date: Sat, 29 Apr 2017 12:43:11 +0800
    Subject: Subject test =?iso-8859-1?b?5+P14ent8/o=?=
    Message-Id: <8BALAKS761U4.0V1EJV2IQDAR1@Cains-Surface-4>
    To: sample@test.com
    MIME-Version: 1.0
    Content-Type: text/plain; charset=utf-8
    Content-Transfer-Encoding: 8bit
    
    Test Message Body special char çãõáéíóú

It has then sent the message correctly in UTF8, this has worked because MailKit has done the following;

    MAIL: Address=A1@test.com Parameters=BODY=8BITMIME

Which is correct according to the standards.

**Comment by cosullivan** [comment]
@reinaldocoelho FYI, I've pushed a branch to MASTER which has your bugfix and also the ability to set the default encoding, however, I don't think this is actually needed.

**Comment by reinaldocoelho** [comment]
Hi @cosullivan  :-)

I have one more point to test, I uploaded to production a forked version of code with UTF-8 fixed to receive e-mails, but e-mails with ISO8859-1 chatset breaked.

To test implementation, we can use this code where I sent more than one chatset e-mails:
https://github.com/reinaldocoelho/Send8BitEmailExample

I executed this test and e-mail with charset ISO8859-1 breaked too, I looked for the problem and think that the problem is that we need to parse e-mail to discovery the correct encode. In this way, we need to start receive the lines and when we found the text "charset=utf-8" wee need to read next lines converted to that encode. 

This make sense?

Thanks for all.

**Comment by cosullivan** [comment]
Hi @reinaldocoelho,

Do you need to make the transfer encoding 8bit? Why not use Base64?

    body.TransferEncoding = TransferEncoding.Base64;

Then, on the server's SaveAsync() method you can do the following;

    var m = MimeKit.MimeMessage.Load(new MemoryStream(System.Text.Encoding.UTF8.GetBytes(message.Mime.ToString())));
    Console.WriteLine(m.Subject);
    Console.WriteLine(m.TextBody);

And that displays the values correctly?

Thanks,
Cain

**Comment by reinaldocoelho** [comment]
So I do not have the control of the email client, we use this SMTP server so that clients of our application can receive emails online, and this encoding problem is being reported by a client that receives emails from this form. Unfortunately, I can not make any changes to the part of the client that is sending it.

This way, I need to tune our SMTP system, which uses your library, to behave properly, regardless of how the client sends it.

Today our basis of comparison is Gmail, if it receives the same or similar email correctly, we also need to interpret correctly.

I'll try to find a way to support these variations and if I can send a PullRequest to receive feedback from you :-)

Thank you very much.

**Comment by cosullivan** [comment]
Yes, I suspect that GMail does do alot more outside of the offical RFC's in order to accept as many emails as possible.

The interesting thing with my example above is that it looks like it may have been double UTF8 encoded, so I will take another look at that.

If you have a look at my v3.0 feature branch that I am working on, I am working on a new method of reading the message content which includes parsing the MIME message (headers and content) such that each section can be read correctly during deserialization. 

https://github.com/cosullivan/SmtpServer/blob/feature/3.0.0/Src/SmtpServer/Mail/MimeMessageSerializer.cs

My plan is to read the contents of the MIME message/entities and pass them on as byte arrays along with the message headers. They can then be deserialized according to the correct format as required.

Thanks,
Cain

**Comment by cosullivan** [comment]
Hi @reinaldocoelho ,

I just pushed an update to the feature/3.0.0 branch which looks like it might be close to being correct, as it handles the output of that Send8BitEmail.

I am stilling using MimeKit to deserialize the message as you can see here;
https://github.com/cosullivan/SmtpServer/blob/feature/3.0.0/Src/SampleApp/ConsoleMessageStore.cs

But the difference is that I am carrying the message contents now as a byte stream rather than using a string builder and thus it should avoid any issues with double encoding which I believe might have been occurring.

It is still a work in progress, and I think there are some issues around the removal of the dot-stuffing which I need to figure out (probably by writing some more tests).

Thanks,
Cain

**Comment by reinaldocoelho** [comment]
Hi @cosullivan 

Thanks for response.
I think your idea is great, returning the received content in bytes to requester and allow them to make what he want with content.
To validate the dot in the end of received content you need to continue use ASCII to found the point, is that?

I will test your branch and look for your idea of return all bytes to solve my problem until version 3.0 was finished.

Thank you.
Reinaldo.

**Comment by cosullivan** [comment]
Hi @reinaldocoelho ,

No, the full stop is just a byte value of 46, so the terminating sequence is a sequence of 13, 10, 46, 13, 10 regardless of the messages actually encoding.

I'm not sure how that would work with BINARY data though (as I think that is fixed length), but in theory the client shouldn't send binary data because the server doesn't yet advertise support for it.

Thanks,
Cain

**Comment by reinaldocoelho** [comment]
Hum, I undestand your point, but NetworkStream is not a binary data?

And about terminating sequence, can it change with SO, correct?
Because:
\n - UNIX   
\r\n - DOS   
\r - Mac 

Thanks,
Reinaldo.

**Comment by cosullivan** [comment]
Yes it is, it just reads bytes. If you put a StreamReader on top of it, then you have the ability to turn those bytes into other things, ie, strings.

The terminating sequence in the SMTP protocols is always the same, regardless of the operating system. Ie, it's always defined using the lexical tokens of CR & LF which are 13 & 10 respectively.

See the section on "Lexical Tokens" here;
https://www.ietf.org/rfc/rfc822.txt

Therefore, if a mail client on the Mac sent a message, it would still be sending \r\n even though that doesn't represent a new line on the mac, but it does in the world of SMTP.

**Comment by cosullivan** [comment]
Hi @reinaldocoelho ,

If you look at the feature/3.0.0 branch now, it seems to be working. It handles your test app when combined with MimeKit.

It's probably not production ready yet given the refactoring I have done, but looks pretty close.

Thanks,
Cain

**Comment by reinaldocoelho** [comment]
Cool Cain, I will get this version and make tests.

Thanks.

**Comment by cosullivan** [comment]
FYI, I've just pushed another set of changes to feature/3.0.0 and it looks pretty good now. All of the tests are passing and my load test runs perfectly fine.

**Comment by reinaldocoelho** [comment]
Cool @cosullivan !!

Thank you.

**Comment by cosullivan** [comment]
@reinaldocoelho , FYI - I've just pushed v3.0.0 to Nuget.

Thanks for all your help on this one.

**Comment by reinaldocoelho** [comment]
Thank you @cosullivan .

I´m testing 3.0 version but I has compiled my own nuget version. After conclude my changes I will point to your version.

Thanks again and for all help.

If I can help in anything, please tell me.

Reinaldo.
