### ISSUE TITLE
Can this SmtpServer send emails?

### ISSUE THREAD

**Issue by sgabler-solytic** [cosullivan/SmtpServer#180]
Hi, I recently used this tool to build a gateway to receive emails. This works really well and it was a pleasure to work with it 👍 

I've studied some logs I implemented, and I found that apparently the server receives SPAM. I can ignore those emails with code. But this triggered another thought that some bots could find this SMTP server automatically and try to use it to send emails.

Just to be 100% sure: in the current version, can this tool be abused to send email? I am almost certain that the answer is "No", but I'd love to get confirmation if possible :)

**Comment by cosullivan** [comment]
Hi @sgabler-solytic ,

No, it can't be used to send emails unless you actually build that functionality in.

Thanks, Cain.
