### ISSUE TITLE
Token.Equals() bug ?

### ISSUE THREAD

**Issue by geoxel** [cosullivan/SmtpServer#196]
https://github.com/cosullivan/SmtpServer/blob/2b9cefff54d5ea19669ec417f2cc569ab0137387/Src/SmtpServer/Text/Token.cs#L99

Maybe should it be :

```
return Kind == other.Kind && ToText().Equals(other.ToText(), StringComparison.OrdinalIgnoreCase);
```

**Comment by cosullivan** [comment]
Yes, you are correct that this is wrong. It's not actually used anywhere that it can cause an issue so I've actually removed support for Equals on the token itself.
