### ISSUE TITLE
How SmtpServer sends email message to smtp.gmail.com

### ISSUE THREAD

**Issue by sokhibjaynarov** [cosullivan/SmtpServer#197]
this project able to receive mail message from gmail.com to come own mail address. But how we can send mail message from own address to Gmail

**Comment by jlunman** [comment]
This library is only for receiving messages as an SMTP server. To send messages, you need an **SmtpClient**, like the one in [MailKit](https://github.com/jstedfast/MailKit). There's also a built-in `System.Net.Mail.SmtpClient` in .NET, but [it is considered obsolete](https://learn.microsoft.com/en-us/dotnet/api/system.net.mail.smtpclient?view=net-7.0#remarks), and only preserved for backward compatibility. MailKit's SmtpClient is recommended instead.
