### ISSUE TITLE
Is there support for spam and viruses filtering? Or a spamhaus check?

### ISSUE THREAD

**Issue by zxcvqwerasdf** [cosullivan/SmtpServer#199]
Question in subject. Ty.

**Comment by WaldenL** [comment]
Define "support." This package handles the network-side SMTP communication. You can then store that message anywhere you want, and, of course, you can do anything with the message as part of that store. You could scan the message content with your own scanners, you could use clam, you could invoke spamhaus, or anything else you wanted to. But the key word is "_**you**_". The package itself it not responsible for what you do with the message.

**Comment by reinaldocoelho** [comment]
You can use other system linked too.
Like: https://spamassassin.apache.org/

Just to add an information :-P
