### ISSUE TITLE
Not calling custom authenticator

### ISSUE THREAD

**Issue by mohrtan** [cosullivan/SmtpServer#20]
I copied your example code exactly and it is not calling my custom authenticator.
```
var options = new OptionsBuilder()
   .ServerName("localhost")
   .Port(25, 587)
   .MessageStore(new ConsoleMessageStore())
   .MailboxFilter(new MailboxFilterFactory())
   .UserAuthenticator(new UserAuthenticator())
   .Build();

var smtpServer = new SmtpServer.SmtpServer(options);
await smtpServer.StartAsync(CancellationToken.None);
```
Then,

```
public class UserAuthenticator : IUserAuthenticator
{
  public Task<bool> AuthenticateAsync(string user, string password)
  {
    Console.WriteLine("User={0} Password={1}", user, password);
    return Task.FromResult(user.Length > 4);
  }
}
```

Console debug line is never displayed and breakpoints are never hit. I'm sending the messages with:
```
using (var client = new SmtpClient(host, port))
{
  client.Credentials = new System.Net.NetworkCredential("yourusername", "yourpassword");
  client.UseDefaultCredentials = false;
  await client.SendMailAsync(FakeMessage);
}
```
Please advise.

**Comment by cosullivan** [comment]
Hi @mohrtan,

With the native SmtpClient, it will only send the authentication information if the EnableSsl property is also set to true.

However, if you set this to true, it will expect the server to advertise support for the STARTTLS command so it can initiate a secure connection. The SmtpServer component does support the STARTTLS, but you need to configure a certificate first.

I am working on v3.0 at the moment, and once I have finsihed that I will be building up some more extensive samples, however, there is an indication as to how to set the certificate in the code here;
https://github.com/cosullivan/SmtpServer/blob/master/Src/SampleApp/Program.cs

Another alternative is to use the MailKit package as that allows you to specifically authenticate against the server I believe.

Thanks,
Cain

**Comment by mohrtan** [comment]
Thanks! I'll try that about asap.
