### ISSUE TITLE
Point removal broke e-mails.

### ISSUE THREAD

**Issue by reinaldocoelho** [cosullivan/SmtpServer#21]
Hi @cosullivan, how are you?

I got a problem with some emails that I received on the server and I'm doubtful if it could be a component error.

I noticed some e-mails presenting errors in signatures, images, font size and others, checking the cases, all at first seemed to present the lack of a dot (".") In some part of the e-mail.

Some cases the email would be in the first position of the next line.

I noticed this piece of code in the system I would like to understand if it might be related:

## DataCommand.cs Line 97
                {
                    // need to trim the '.' At the start of the line if it
                    // exists this would have been added for transparency
                    // http://tools.ietf.org/html/rfc5321#section-4.5.2
                    Context.Transaction.Mime.AppendLine (text.TrimStart ('.'));
                }

If I understood correctly, the excerpt "text.TrimStart ('.')" Will remove the point if this is the first character of the line. From what I've seen in my EMLs, the problem must be just that.

Verifying your comment, I did not understand if the indicated "period" of the text to be removed should even be a point, and if yes, I did not understand the logic.

Could you help me to understand this point better?

Thank you

**Comment by cosullivan** [comment]
Hi @reinaldocoelho,

A message is completed by the mail client sending a <CRLF>.<CRLF> sequence, effectively, a full stop that exists on a line all by itself. 

Therefore, if for some reason the message was to contain a full stop on a blank line the mail server could incorrectly deem this to be the end of the message. To avoid this, the mail client will send two full stops together so one needs to be removed.

Interestingly though, I wonder how some mail clients are sending if the line begins with a full stop, but also contains other characters. Perhaps some mail clients arent working correctly.

if you look at the RFC, it explains what should happen from the point of view of the server;
https://tools.ietf.org/html/rfc5321#section-4.5.2 

Note that I am working on v3.0 functionality now which is around how the server is receiving the messages. Currently, I don't really care about the data that is being received and in most cases this is fine, however, as you have seen previously this causes issues with Unicode messages. To handle Unicode messages correctly (aswell as binary messages) I need to parse the message format and pay attention to the MIME format.

You can follow my progress in this branch if you like;
https://github.com/cosullivan/SmtpServer/tree/feature/3.0.0

But please note that it is currently very much a work in progress.

Thanks,
Cain

**Comment by cosullivan** [comment]
@reinaldocoelho 

Are you able to send me some of the emails that have issues?

**Comment by reinaldocoelho** [comment]
Hello @cosullivan.

Yes, it follows attached an EML that broke the image because it misses a dot.

[Email-dot-removed.zip] (https://github.com/cosullivan/SmtpServer/files/955159/email-dot-removed.zip)

The excerpt that asked the point is this:

None; Margin-left: 30px; User-select: none; "src = 3D" https: //intranet.alatur=
Com / assets / custom / img / signature / 2016 / logos / seal-25.jpg "> </a> </ td>

The url of the image is: https: //intranet.alaturcom/assets/custom/img/assinatura/2016/logos/selo-25.jpg

But the correct one would be:
Https://intranet.alatur.com/assets/custom/img/assinatura/2016/logos/selo-25.jpg

I know it's not a subscription issue, because we received several other emails from this sender without problem from the point in the image.

Thank you very much.

**Comment by cosullivan** [comment]
Hi @reinaldocoelho,

I see what you mean here. The only thing I can think of is that the mail client isn't sending the additional full stop, but perhaps that's not required because it is using quoted-printable encoding. In theory though, the transparency of the mail content should preceed the MIME content transfer encoding.

If you look specifically at the following;
"If the first character is a period and there are other characters on the line, the first character is deleted."

So that does mean that if the message came through and the first character was the period, in which case it was, the SmtpServer will be taking that out. 

I'm not sure what the solution here is though, but I will probably find out shortly as I will be implementing the quoted-printable encoding of the message.

Thanks,
Cain

**Comment by reinaldocoelho** [comment]
I had some doubts about the RFC, I will read the document properly (https://tools.ietf.org/html/rfc821) in the Transparency session to see if I understand better.

But I understood your point of view, because I understand what the customer should when they find that period, add an additional period on start of line.

Do you think the SMTP server should somehow be concerned about this client error?

Thanks,
Reinaldo.

**Comment by reinaldocoelho** [comment]
Hi @cosullivan.

I was checking the case I commented from TrimStart () and the RFC. Actually the RFC says that the client should send the point 2 times and that the server should remove the first point of the line.

I was checking the TrimStart () command and it removes not only the first but all the first points of the line, like the example below.

    class Program
    {
        static void Main(string[] args)
        {
            string x = ".abc123456";
            string y = "..abc123456";
            x = x.TrimStart('.');
            y = y.TrimStart('.');
            Console.WriteLine(x);
            Console.WriteLine(y);
        }
    }

If you run this code, you will see that the colon is removed from the second variable.

I believe this is the cause of the Bug :-)

**Comment by reinaldocoelho** [comment]
I created a PullRequest #23 to that.

Thanks.

**Comment by cosullivan** [comment]
Ahh, of course. Good pickup!!
