### ISSUE TITLE
Provide a working sample with SSL

### ISSUE THREAD

**Issue by bernharde** [cosullivan/SmtpServer#22]
Hi,
first thank you so much for your great work.

I'm trying to get your sample project working with SSL enabled but I'm failing. 
//smtpClient.EnableSsl = true;
EnableSsl does not exists any more
I tried also ConnectSSL and StartTls - both failing, could you please update your sample or provide some information about what is going wrong?

Thanks, Bernhard

**Comment by cosullivan** [comment]
Hi,

Sorry, the previous example was using the System.Net.SmtpClient which had the EnableSsl property. I have now switched to using the MailKit SmtpClient which will automatically enable SSL as long as the server advertises it.

If you look at the SampleApp now (on master);

https://github.com/cosullivan/SmtpServer/blob/master/Src/SampleApp/Program.cs#L29
This is used for development purposes only and allows you to ignore the certificate errors.

https://github.com/cosullivan/SmtpServer/blob/master/Src/SampleApp/Program.cs#L34
As long as you pass the Certificate to the OptionsBuilder, the SmtpServer will advertise the STARTTLS command during an EHLO command.

https://github.com/cosullivan/SmtpServer/blob/master/Src/SampleApp/Program.cs#L125
Once the client connects, the IsSecure property will now display "true" to indicate a secure connection has been achieved. If you remove the Certificate from the options builder and try again, you will see this is "false".

https://github.com/cosullivan/SmtpServer/blob/master/Src/SampleApp/Program.cs#L163
This will show the STARTTLS command has been called.

Let me know if you still have issues.

Thanks,
Cain

**Comment by bernharde** [comment]
Hi Cain,
thanks for your quick and detailed help. I got the sample working with SSL.
