### ISSUE TITLE
Missing “SessionCreated” event in the event of an error at the secure endpoint

### ISSUE THREAD

**Issue by tinohager** [cosullivan/SmtpServer#238]
If a secure session is established on port 587 but no data is transferred and the session times out, no event is triggered. Would there be an argument against triggering the event before the `UpgradeAsync`?

https://github.com/cosullivan/SmtpServer/blob/8a5bce4e42da949422fe5a3182bdaf10efaefe7f/Src/SmtpServer/SmtpSessionManager.cs#L38-L42

**Comment by cosullivan** [comment]
Yes it probably makes sense to move it.

**Comment by tinohager** [comment]
I have made the changes
