### ISSUE TITLE
How to know SSL enabled on Server

### ISSUE THREAD

**Issue by bernharde** [cosullivan/SmtpServer#24]
Hi, 
sorry this is not a real issue - just a question:
I only want to allow SSL connections on the server. How can I check, whether the connection is secure and the mail is coming over SSL on the server side? 

Thank you for your help.

Best regards,
Bernhard E

**Comment by cosullivan** [comment]
Hi,

There are two ways to do this at the moment;

The IMailboxFilter and IMessageStore interfaces both take in an ISessionContext parameter.  You could cast that to an ISmtpSessionContext and in which case that exposes a Text property which has an IsSecure property which would be true or false.

Additionally, you can add an event handler to the ISessionContext.CommandExecuting event and listen out for the StartTlsCommand to be issued.

The first option would probably be the easiest. I will promote the IsSecure property onto the ISessionContext in the next version such that you don't need to perform this casting.

Thanks,
Cain

**Comment by bernharde** [comment]
Thank you once again!

So one further step would be only allowing secure transport. Returning error code 530 would be correct or?
