### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by 304NotModified** [cosullivan/SmtpServer#26]
Hi,

Is there a changelog? If not, please create them or use GitHub milestones/releases. 

Thanks for the awesome lib! Used it with pleasure in an unit test for NLog :)

**Comment by cosullivan** [comment]
Hi, 

Thanks for the feedback, I'm glad you enjoyed using it.

I am planning on spending a bit of time working on additional samples and including change logs in the next few months so will start to incorporate them. 

Thanks,
Cain.

**Comment by 304NotModified** [comment]
:+1:
