### ISSUE TITLE
is "no reply <do_not_reply@domain.com>" supported?

### ISSUE THREAD

**Issue by 304NotModified** [cosullivan/SmtpServer#27]
Is this format supported?

    no reply <do_not_reply@domain.com>

e.g. `Mime.ToString()`

```
From: hi@unittest.com
Date: Thu, 01 Jun 2017 19:02:17 +0200
Subject: Message from NLog on DELL-JULIAN
Message-Id: <BXULFAJEG1U4.D56WL1F28ATH3@localhost.localdomain>
To: mock@mock.com
Cc: no reply <do_not_reply@domain.com>

```

But `DisplayName` is `null`

![image](https://cloud.githubusercontent.com/assets/5808377/26691366/22115932-46fd-11e7-8c21-4631ac443ee0.png)

**Comment by 304NotModified** [comment]
this is version 2.2, but the same result is in 3.0

**Comment by cosullivan** [comment]
Hi, that DisplayName property has been obsolete for a while now so I've just removed it as it is misleading.

What you've posted are the message headers of the MIME content which will be different to the From and To properties that are on the message transaction. The From and To properties (which are collections of IMailbox) are taken from the MAIL and RCPT commands that are sent from the mail client and don't include a display name.

These will be different under a number of circumstances, for example, if you added another address as a BCC, this wont appear in the MIME content, but is included in the message transaction from one mail server to another.

Thanks,
Cain.

**Comment by 304NotModified** [comment]
Do you mean obsolete in your code? Or some RFC? 

If it's the first, please add a `[Obsolete]` attribute

**Comment by cosullivan** [comment]
Hi, Obsolete in my code - It was originally used for something else, the RFC doesnt support it.

rcpt = "RCPT TO:" ( "<Postmaster@" Domain ">" / "<Postmaster>" /
                  Forward-path ) [SP Rcpt-parameters] CRLF

Thanks,
Cain.
