### ISSUE TITLE
Pattern for unit test

### ISSUE THREAD

**Issue by 304NotModified** [cosullivan/SmtpServer#28]
I'm using this library in an unit test.

What's the best pattern to use this? It's not fully clear to me when I could start reading.

Currently I have this: ([full code](https://github.com/NLog/NLog.MailKit/blob/master/test/NLog.MailKit.Tests/MailTargetTests.cs))

```c#
var countdownEvent = new CountdownEvent(1);

... //create SMTP server 
smtpServer.StartAsync(cancellationToken.Token);        

... //send mail

countdownEvent.Wait(TimeSpan.FromSeconds(10)); //wait max 10 sec

...//do assertions

cancellationToken.Cancel(false); //done, cancel for new test
```

It works, but it's a bit unstable.

Thanks for your advise!

**Comment by cosullivan** [comment]
Hi,

You should be able to start receiving messages as soon as the call to the StartAsync method returns. I have a few unit tests which do this here;
SmtpServer.Tests/SmtpServerTests.cs

What errors are you getting? I will clone your project a bit later when and can have a look too.

Thanks,
Cain.

**Comment by 304NotModified** [comment]
Well sometimes it won't work (not receiving messages). But maybe are the tests running in parallel, have to check that first.

So this pattern is correct?

**Comment by cosullivan** [comment]
Yes, that should be fine - in my tests I am waiting for the task and handling the cancellation exception, but in theory there is no need for that.

It sounds more likely to be an issue with having the tasks run in parallel and potentially the availability of the ports.
