### ISSUE TITLE
Add the remote IP to the SaveAsync method

### ISSUE THREAD

**Issue by LordMike** [cosullivan/SmtpServer#3]
Hi,

I was looking for a good C# SMTP server for a small project, and lo and behold. This looks really great. 

I'm lacking a little on the hooks though, as the MessageStore seems to lack a number of things. All it really has access to is the actual message itself - not the IP f.ex. For my project, I need to store the IP of the remote client sending data.

For extra points, I'd love to store the commands sent/received in a specific session as well. But that's for another day.

I was playing around a little, and I added the `EndPoint` to `ISmtpSessionContext`. When it's created by `SmtpSession`, I then grab the `TcpClients` remote endpoint and store it. `SaveAsync` for the message can then be extended to include the remote endpoint. But I'm unsure if this is the best way.

In order to extend it, it might make sense to create a "context" (or extend the existing) which then contains this info. Thoughts?

Mike.

**Comment by cosullivan** [comment]
Hi Mike,

Glad to hear you like my project.

The ISmtpSessionContext already contained the EndPoint of the remote client as I added it a few months back to allow the IMessageFilter to filter based on IP. 

I had already modified the IMessageStore to support the same approach (ie, having a CreateSessionInstance method) but hadn't pushed that change. Based on your feedback, I have change that interface such that the CreateSessionInstance methods now take in an ISessionContext which has the EndPoint on it now. This could easily be extended now in the future while maintaining API compatibility. Have a look at my latest commit and let me know what you think.

Internally there is also an IStmpSessionContext which implements ISessionContext but has additional internal state about the session.

In terms of wanting to store a history of the commands, that would be a relatively easy thing to add onto the ISessionContext as you could simply just add an instance of hte SmtpCommand object that was executed. These SmtpCommand objects are all immutable and expose their relative properties, ie, the HeloCommand contains the Domain property etc. I guess the issue with doing it on the session context though is what is the scenario that you want to log the commands for? If they were all added to the ISessionContext then there is only two hooks where they could be seen, one at the filtering stage and the other when saving the message. Neither of those hooks are the end of the session though as the client could then execute more commands after that.

Perhaps the SmtpServer class itself needs to support some events such as SessionCompleted which then also passes the ISessionContext as a parameter on the EventArgs? Thoughts?

Thanks,
Cain

**Comment by LordMike** [comment]
Great!
 
I'm unsure about what I want the log for right now. So I wouldn’t go far down that road. I think the initial thought was that I wanted an SMTP server that would respond according to the protocol and then just accept everything. I would then save the log somewhere, and then parse that later on.

I'm making an SMTP black hole server, to receive any message and present them. Much like Mailinator, but for internal use. It's intended to receive malicious content and present it to the users in a safe manner (hopefully preventing users from receiving malicious mails in their Outlook inboxes instead). 

But of course you're right. I suppose many MTA's batch their mails in a single connection for performance reasons, making my approach impossible (one session equals many mails suddenly).
 
I will most likely handle each SaveAsync call and parse out the MIME message (to get stuff like from, to, subject, attachment counts..) and then otherwise store all data raw. The only thing I was missing was the IP. (So I can present it to the user, do SPF checks, spam blocklists etc.).

If I were to do anything now, I would do it for logging. So a server could log somewhere that it received these messages (and that some of them may have been bogus etc..). This would be to do "verbose" logging or to aid in troubleshooting clients. But I wouldn't do it for my reasons.

**Comment by LordMike** [comment]
I was wondering about your pattern (The `CreateSessionInstance` thing). Why not give the context to each method, and then keep only one of each provider?

It seems a waste to me to create a new instance of the `MessageStore` just to keep one local variable. F.ex., in my message store, I will want to keep stuff like DB connections, but not one copy of these instances/settings for each message that comes in.

**Comment by cosullivan** [comment]
Hi Mike,

I find that pattern useful when using IoC as it allows the instance itself to act as a factory for other instances. Say for example you were performing some whitelist filtering you could do something such as returning a difference class altogether for an invalid client (ie, a SpamMessageStore) versus an acceptable message.

I rarely develop any projects these days without using a container so a lot of my patterns are geared towards that. It's also very similar to how the Web API implements a few things, ie, the GetPerRequestFormatter method on the MediaTypeFormatter.

Thanks,
Cain

**Comment by LordMike** [comment]
Does this also work in the case when the produced instance will contain values specific for a single session? I'm all for factories creating generic handlers like SpamMessageStore or DbMessageStore etc, but they're really should only be one.

But then again - I'm no expert on patterns :P

**Comment by cosullivan** [comment]
I made a change to this over the weekend to separate the factory from the implementation interface. You will notice now that there is an IMessageStoreFactory that has a CreateInstance method which takes in the ISessionContext and also the IMessageStore interface's SaveAsync method also takes in the ISessionContext. This should allow the best of both worlds, the only additional overhead now is that you have to provide a factory instance rather than directly an IMessageStore instance. If you use the base abstract MessageStore class though, this actually implements both IMessageStoreFactory and IMessageStore and just returns itself as the instance.

Thanks,
Cain
