### ISSUE TITLE
[Question] Authentication

### ISSUE THREAD

**Issue by MaddalenaTech** [cosullivan/SmtpServer#30]
How to know if the context is authenticated ? (and maybe the relative username)

**Comment by cosullivan** [comment]
Hi,

At the moment the ISessionContext has a SessionAuthenticated event that you can subscribe to. You can get access to the ISessionContext when a new session is created through subscribing to the SessionCreated event on the SmtpServer instance itself. 

In the next release I have added an IsAuthenticated property onto the ISessionContext interface itself such that it is easily accessible.

Thanks,
Cain.

**Comment by cosullivan** [comment]
I should also mention that in terms of the username, this isn't directly supported. In the next version though, I have added a Properties property (IDictionary<string, object>) to the ISessionContext interface that acts as a general area to maintain custom state for a session.

In this case, you will be able to assign the user name to this session state during the call to your authentication method (which I am also introducing the ISessionContext to that interface too).

Thanks,
Cain.
