### ISSUE TITLE
VS 2015 and .Net

### ISSUE THREAD

**Issue by Dafnafrank** [cosullivan/SmtpServer#32]
We are using your wonderful server. Thank you very much!
We wanted to ask you if you can make a VS 2015 with .Net (not core) version...?
Since you moved to 2017 we cannot use your server since we do not work with .Net Core nor VS 2017

**Comment by cosullivan** [comment]
Hi,

Thanks for your feedback.

Are you building the project yourself? If so, can you not use the packages from NuGet? I can add a VS2015 version, but just want to see if there are other options before I start maintaining another solution.

Thanks,
Cain.

**Comment by Dafnafrank** [comment]
Yes, We are building the project ourselves (after downloading) and referencing it.



Sent from my iPhone

On 7 Jun 2017, at 17:47, cosullivan <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

Thanks for your feedback.

Are you building the project yourself? If so, can you not use the packages from NuGet? I can add a VS2015 version, but just want to see if there are other options before I start maintaining another solution.

Thanks,
Cain.

**Comment by cosullivan** [comment]
Ok, I will add a VS2015 solution in the next few days.

Thanks,
Cain.

**Comment by cosullivan** [comment]
Hi Dafna,

I've pushed pushed a version that contains a VS2015 solution.

Thanks,
Cain.

**Comment by Dafnafrank** [comment]
This is great!
Thank you!!

Sent from my iPhone

On 11 Jun 2017, at 16:11, cosullivan <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Dafna,

I've pushed pushed a version that contains a VS2015 solution.

Thanks,
Cain.
