### ISSUE TITLE
Add cassandra as storage message

### ISSUE THREAD

**Issue by ryzam** [cosullivan/SmtpServer#33]
Hi .. i already fork and add some initial code to work with Cassandra as storage db

**Comment by cosullivan** [comment]
Hi,

Thanks for your interest. 

At this stage I am not keen on adding additional message stores into my branch as I want to keep the dependencies on the package to the absolute minimum.

This type of thing would be good as a separate package in its own right, ie, SmtpServer.Storage.Cassandra.

If you create a separate project, let me know and I will follow your progress.

Thanks,
Cain.

**Comment by ryzam** [comment]
Do you have any project roadmap ? And any plan to build complete Mail Server for .Net?

**Comment by cosullivan** [comment]
Hi,

At the moment I am just going to focus on building up some more samples and support a few more of the RFCs (BDAT, International Email address).

I don't have any plans at the moment to build a complete mail server as I have something close to that for a non-open source project, and hence why I built this component in the first place.

Thanks,
Cain.
