### ISSUE TITLE
Can't inspect Bcc's

### ISSUE THREAD

**Issue by molynerd** [cosullivan/SmtpServer#35]
I'm using this to help write some unit tests for a mail client, but it looks like i can't inspect the Bcc's when receiving the message in the message store.

I've validated that sending the exact same message to something like smtp4dev works just fine and the Bcc's are properly listed there.

![image](https://user-images.githubusercontent.com/6462105/26989200-0f12de18-4d07-11e7-9db2-1414fddc5a6e.png)

**Comment by cosullivan** [comment]
Hi, 

The BCC property is not transmitted in the actual MIME content as this would then go against the purpose of the BCC (in that those recipients should not be known to the receiver). 

The BCC addresses are available to the mail server through the message transaction. For example, when the mail client (if it is acting as a relay server) sends the message to the server, it simply tells the server who the message is being sent from, and all of the recipients that it assumes exists on this mail server. You email may have 10 different email address, but the relay server would only send those gmail address to the gmail server and so forth.

If you want to know the list of email address that the client has sent to the server, these are available on the IMessageTransaction interface).

I have added a test case for this here so you can see how it works;
https://github.com/cosullivan/SmtpServer/blob/master/Src/SmtpServer.Tests/SmtpServerTests.cs#L131

I'm not sure what smtp4dev would be doing in this case, but the mail client should never be sending them.

Thanks,
Cain.

**Comment by molynerd** [comment]
@cosullivan

> Is this your own mail client? If it is, and you are sending the BCC fields then they should still be sent through to the server in the MIME content, so perhaps it is that MimeKit is ignoring them.

Yeah, all I meant by this issue is that I wasn't able to test whether the BCCs were there, even though the mail is sent/received successfully and correctly.

Thanks for putting the test out there. I didn't consider looking in the `To` prop to see if they were there. You can go ahead and close this one out.

**Comment by justinjstark** [comment]
For others who stumble upon this, I'm using the code below to add the BCC emails back in for my specific use case:

```cs
var messageEmails = message.To.Union(message.Cc)
    .OfType<MailboxAddress>() //Drops GroupAddresses
    .Select(ma => ma.Address.ToLower());

var transactionEmails = transaction.To.Select(m => m.AsAddress().ToLower());

var bccEmails = transactionEmails.Except(messageEmails);

foreach(var bccEmail in bccEmails)
{
    message.Bcc.Add(new MailboxAddress(bccEmail));
}
```

**Comment by vesnaveen** [comment]
Great! This logic is perfectly working.

**Comment by vesnaveen** [comment]
Hi @justinjstark 
this code is working and finding the actual bcc but sometimes its consider when mutiple To address then take bcc even its not send Bcc my smtp client. its very rare case but this happeing and I dont identifing the issue. could you suggest in this issue. 

`var messageEmails = message.To.Union(message.Cc)
    .OfType<MailboxAddress>() //Drops GroupAddresses
    .Select(ma => ma.Address.ToLower());

var transactionEmails = transaction.To.Select(m => m.AsAddress().ToLower());

var bccMailboxAddresses = transactionEmails.Except(messageEmails)
    .Select(s => new MailboxAddress(s));

message.Bcc.AddRange(bccMailboxAddresses);`
