### ISSUE TITLE
User Authenticator not executed

### ISSUE THREAD

**Issue by molynerd** [cosullivan/SmtpServer#36]
Looks like a wired up IUserAuthenticator doesn't actually get used. Can you add a unit test so that I can validate my implementation, as well as validating the code works? I'm doing a fairly simple `SmtpClient.Credentials = new System.Net.NetworkCredential("testuser", "testpass"), but the `AuthenticateAsync(string, string)` method is never called.

**Comment by cosullivan** [comment]
Hi,

There are two other things you will need. By default, the AUTH command wont be advertised to the client unless the UserAuthenticator has been set (which you have) and the connection is secure (via the client calling the STARTTLS command). The STARTTLS command isn't advertised unless you supply a certificate.

If you want the AUTH command to be available on an unsecure connection, then call the "AllowUnsecureAuthentication" option on the builder.

I have created a test here;
https://github.com/cosullivan/SmtpServer/blob/master/Src/SmtpServer.Tests/SmtpServerTests.cs#L87

Thanks,
Cain.

**Comment by molynerd** [comment]
@cosullivan oh man, sorry about that. Obviously one would need a cert to do TLS. I don't know how that slipped my mind.
