### ISSUE TITLE
Font size problem

### ISSUE THREAD

**Issue by Dafnafrank** [cosullivan/SmtpServer#37]
Hi,

Thank you for your great SmtpServer. We have been using it quite some time.

We encountered an issue  with the Smtp Server that we wanted to consult with you.
In SmtpCommand.cs
```
while ((text = await context.Text.ReadLineAsync(TimeSpan.FromSeconds(60), cancellationToken).ConfigureAwait(false)) != ".")
                {
                    // need to trim the '.' at the start of the line if it 
                    // exists as this would have been added for transparency
                    // http://tools.ietf.org/html/rfc5321#section-4.5.2
                    **context.Transaction.Mime.AppendLine(text.TrimStart('.'));**
                }
```
We think that the above highlighted code causes the below problem.

Problem:
When mime part is text/html and the CRLF is located right after the numeric part of the font size declaration, 
removing the first period in the following line causes the font to be bigger.

For Example:
Original mail:
le=3D'font-size:11.0pt;font-family:"Calibri",sans-serif;color:windowtext'>=
Outlook</span><span dir=3DRTL></span><span style=3D'font-size:11.
0pt;font-family:"Arial",sans-serif;color:windowtext'><span dir=3DRTL></sp=

After parsing we receive the mail with bigger font:
le=3D'font-size:11.0pt;font-family:"Calibri",sans-serif;color:windowtext'>=
Outlook</span><span dir=3DRTL></span><span style=3D'font-size:11=
0pt;font-family:"Arial",sans-serif;color:windowtext'><span dir=3DRTL></sp=

The " ." has been lost. 
This causes the font size to be suddenly bigger

The way found to fix this is as follow:

```
while ((text = await context.Text.ReadLineAsync(TimeSpan.FromSeconds(60), cancellationToken).ConfigureAwait(false)) != ".")
                {

                    string tmp = text;
                    if (text.Length > 0 && text[0] == '.')
                        tmp = text.Substring(1);
                    context.Transaction.Mime.AppendLine(tmp);

                    // need to trim the '.' at the start of the line if it 
                    // exists as this would have been added for transparency
                    // http://tools.ietf.org/html/rfc5321#section-4.5.2
                    //context.Transaction.Mime.AppendLine(text.TrimStart('.'));
                }
```

We would appreciate your thoughts about this issue.

**Comment by cosullivan** [comment]
Hi,

Yes, this was a known issue previously and was fixed in the v3.0.0+ version. I assume you must still be using the 2.2 version from a while back.

If you update to the current version that should be solved.

Thanks,
Cain.
