### ISSUE TITLE
options.AuthenticationRequired() causes connection abort

### ISSUE THREAD

**Issue by xsharper** [cosullivan/SmtpServer#39]
If authentication is required , client connection is aborted when user attempts to login.

Can be easily reproduced in SessionContextExample sample code, just by requiring authentication in options.

Can fix like:

    void OnSessionAuthenticated(object sender, EventArgs eventArgs)
    {
            _context.SessionAuthenticated -= OnSessionAuthenticated;

            WaitingForMail.Clear(AuthCommand.Command);
            WaitingForMailSecure.Clear(AuthCommand.Command);

            if (_options.AuthenticationRequired)
            {
                // << PATCH
                WaitingForMail.Clear(MailCommand.Command);   
                WaitingForMailSecure.Clear(MailCommand.Command);
                // PATCH >>

                WaitingForMail.Add(MailCommand.Command, TryMakeMail, SmtpState.WithinTransaction);
                WaitingForMailSecure.Add(MailCommand.Command, TryMakeMail, SmtpState.WithinTransaction);
            }
        }

Or, better, get State.Add to work as (currently unused) State.Replace in all cases. This also fixes another problem, as currently multiple emails per-session cannot be sent. E.g.

    HELO xxx
    MAIL FROM: <sender@x.com>
    RCPT TO: <recipient1@x.com>
    DATA
    ...
    RSET
    MAIL FROM: <sender2@x.com>

**Comment by cosullivan** [comment]
Thanks for finding that, it was a bug that was recently introduced.

I have now fixed it and uploaded a new NuGet package.

Thanks,
Cain.
