### ISSUE TITLE
Connection closes

### ISSUE THREAD

**Issue by LordMike** [cosullivan/SmtpServer#4]
Hey,

While testing, I start and stop my server a lot. I've found that once in a while, when the server starts, it will drop the first connection.

![image](https://cloud.githubusercontent.com/assets/1027111/16356128/030e62d2-3ace-11e6-83c3-6b211a0e4dc4.png)

I'm unsure what causes this - as the server runs fine for long periods of time. In the picture, I run the server two times. The first receives 10 messages without issue, but then it's restarted and suddenly the first message connection is closed by the server.. Messages after that initial closed connection will do fine.

I could dig deeper, but I'm out of time right now.

**Comment by cosullivan** [comment]
Hmm, that's interesting. I know there is an issue with the way I am tracking the tasks that each session is creating - the issue exists in the task (ie, message from the sender) is complete because I have a chance to add it to a cache. That's only usually an issue on localhost so I wonder if this is somehow related. I've been meaning to fix that for a while anyway, but I will see if I can replicate your scenario.

**Comment by LordMike** [comment]
It's mitigated by the fact that senders will retry (in theory at least). I can try running this when I get back in a weeks time by catching all exceptions. Should at least give a pinpoint if the issue is there.

**Comment by cosullivan** [comment]
If you get a chance can you please try this again with the latest commits on master? I made some changes to the way that the sessions were tracked, not sure if it will make a difference though.

Also, how are you actually restarting the server?

**Comment by LordMike** [comment]
I pulled the code, then I noticed something weird when I enabled showing all exceptions. Apparently I had called `.Ports()` twice with the same values (I construct an `OptionBuilder` with defaults, and then when loading a config I set it agan).. I've now changed the code so it only sets the ports once.

I have yet to reproduce the dropping connection thing. May be related.

**Comment by LordMike** [comment]
I think I have it. When I send from powershell, I've noticed that only the first message triggers an accepted client (code in `ListenAsync`). This leads me to believe the powershells `Send-MailMessage` keeps a persistent connection. Netstat also shows an established connection between my server and powershell, even after the mail has been sent.

That connection is of course broken when I restart the server, hence the error. So no error on your part.
