### ISSUE TITLE
501 on heavy load

### ISSUE THREAD

**Issue by bernharde** [cosullivan/SmtpServer#41]
At the moment I'm sending a lot of mails concurrently - heavy load test.

I create 100 mails and send them in 3 seconds by using an external smtp server. Only about the half is receiving. For the other half I got errors 501
550 5.0.350 Remote server returned an error -> 501 expected NOOP/RSET/QUIT/RCPT/DATA, 4 retry(ies) remaining. 
In my log I can see that the MailFilter is called successfully all the time (100 times), but the MessageStore is not called. 
Any idea?

Thanks, Bernhard

**Comment by cosullivan** [comment]
Hi,

In terms of the failures you might be experiencing some port exhaustion;
https://msdn.microsoft.com/en-us/library/aa560610(v=bts.20).aspx

If you want to use the server on Windows for high throughput traffic you will need to configure your TCP settings to allow this to occur.

Is your MessageStore not being called for any of those requests? 

What response is your MailboxFilter returning and can you paste the implementation of your MessageStore?

Thanks,
Cain.

**Comment by bernharde** [comment]
Thank you for the hints. Shame On Me. My fault.
Return value in MailboxFilter was wrong sometimes. Now everything is working.

Have a nice day, Bernhard
