### ISSUE TITLE
OptionsBuilder.MaxMessageSize

### ISSUE THREAD

**Issue by ultimategrandson** [cosullivan/SmtpServer#42]
Firstly, I really like what you've done with this :)

I think, MaxMessageSize should be taken into account while the message is being received, it should stop accepting anymore of the message if it reaches the maximum size. Currently, I have put a check into my implementation of IMessageStore, but by the time that is called the message is already fully received.

**Comment by cosullivan** [comment]
Hi, thanks for your feedback.

The message size limit is an interesting one. If the mail client and mail server are both implemented correctly to support the SIZE extension, then the mail server should advertise the maximum message size that it can accept and the mail client should advertise the size of the message it is going to send. In this case, the message can be stopped before it is even sent.

The hard part here is when the mail client either doesn't implement the SIZE extension or chooses to ignore it and then sends a message larger that what the server supports. There are probably 3 different options in this scenario;

1. Accept the entire message and allow it to be handled later on (which is what I am currently doing). The spec actually does state that the mail server can, if it chooses, allow a message to be received that is greater than the agreed upon size. This was probably designed like this to allow for backwards compatibility as all the extensions are.

2. Accept only the maximum size for the message, and continue reading the stream until the mail client has finished sending the message but dropping all the bytes that are sent after the maximum. This is useful in that the mail server can then respond to the mail client when the mail client is ready to receive a message. It's not safe to send an error response back to the mail client if the mail client is not in a state where it is expecting a response.

3. Terminate the session once the maximum message size has been exceeded. This is probably not a nice way to deal with the mail client, but it is by far the safest way for the server (to avoid abusive mail clients).

I have thought about this previously in terms of abstracting that mail message size strategy out such that it can be changed easily depending on what the implementer would like to occur. I will look at implementing this in the coming weeks.

Thanks,
Cain.

**Comment by ultimategrandson** [comment]
Hi, thanks for the reply. 

From my testing, the MailKit library doesn't appear to take SIZE into consideration. At least, when using the standard Send method.

My original thinking was that it should close the session when the size has exceeded but now I'm thinking that could be worse if the mail client was to retry sending the email repeatedly. 

It probably is a better strategy to accept the full email and then reject it. Either that or a combination of rejecting it initially and then if it retries repeatedly; reject it. Abstracting the strategy does sound like a good way to go.

For my requirements, I need it to basically fail as quick as possible. I will likely achieve the best outcome if I can get MailKit to use the SIZE command.

Thanks!

**Comment by ultimategrandson** [comment]
Upon closer look, MailKit does allow you to see the max size, it just doesn't enforce it.
