### ISSUE TITLE
How to return msg on client when facing some exception 

### ISSUE THREAD

**Issue by vesnaveen** [cosullivan/SmtpServer#44]
We send the mail from client and its will get on server. When server executed so how to return message on client when facing some exception in smtpserver and how to client to know that what was my response

**Comment by cosullivan** [comment]
Hi, I'm not really sure I understand your question that well.

What mail client are you using and do have a sample that you can post to help explain your question?

Thanks,
Cain.

**Comment by vesnaveen** [comment]
I am using smtpclient right now.
Here is example for send mail.


using (var SmtpServer = new SmtpClient())
            {
                MailMessage mail = new MailMessage();
                mail.From = new MailAddress("test@gmail.com");
                mail.To.Add("test@test.co.in");
                mail.ReplyToList.Add(new MailAddress("test@gmail.com"));
                mail.Subject = "Test Mail";
                mail.Body = "<b>This is for testing SMTP mail <b>";
                mail.IsBodyHtml = true;
                System.Net.Mail.Attachment attachment;
                attachment = new System.Net.Mail.Attachment(@"e:/JalpiError.txt");
                mail.Attachments.Add(attachment);            
                SmtpServer.Host = "192.168.1.9";
                SmtpServer.Port = 500;
                SmtpServer.UseDefaultCredentials = false;               
                SmtpServer.Credentials = new System.Net.NetworkCredential("testuser", "testpsd");
                SmtpServer.EnableSsl = false;                             
                try
                {
                    SmtpServer.Send(mail);
                }
                catch (Exception)
                {
                    throw;
                }
            }
```

**Comment by cosullivan** [comment]
Hi,

Within the SmtpServer there are different ways for it to return an error, but it all depends on what the client is doing at the time.

In any of the hooks (IMessageStore, IMailboxFilter, or IAuthenicator) you can throw a SmtpResponseException and pass the desired response. It is then up to the individual client as to how that is then handled.

What type of error are you looking for in particular?

Thanks,
Cain.

**Comment by vesnaveen** [comment]
Ohh. I got it now.
I want just return message only when i face exception. I got this solution. your comment was very helpful for me.
Thank You :)
