### ISSUE TITLE
Add Account & Send

### ISSUE THREAD

**Issue by dudeNumber4** [cosullivan/SmtpServer#45]
I give up.  I can't figure out how to create the server, add a user account, & send a message to that account.

**Comment by cosullivan** [comment]
Hi,

There are samples here that should help guide you through the setup;
https://github.com/cosullivan/SmtpServer/tree/master/Src/SampleApp/Examples

In regards to adding a user account, this component is responsible for handling the interaction with the mail clients so managing user accounts is outside of the scope of what this code provides. You can create an instance of an IUserAuthenticator to callback to your user management subsystem (see the samples and test cases for how to use that).

To send a message to it, it will depend on what mail client you are using, but the samples are doing exactly that.

Thanks,
Cain.
