### ISSUE TITLE
message-id retrieving

### ISSUE THREAD

**Issue by pirobox** [cosullivan/SmtpServer#49]
Hi,
   is it possible to retrieve the Message-Id of the message in a custom MessageStore module (or in any other module)?

regards, Andrea

**Comment by cosullivan** [comment]
Hi, 

Yes, you can access the Message-ID as long as you have some way of parsing the MIME content. The easiest way would be to use MimeKit and that will give you a message object that you can then interrogate for the Message-ID.

Thanks,
Cain.

```
public Task<SmtpResponse> SaveAsync(ISessionContext context, IMessageTransaction transaction, CancellationToken cancellationToken)
{
        var textMessage = (ITextMessage)transaction.Message;
        
        var message = MimeKit.MimeMessage.Load(textMessage.Content);
        Console.WriteLine(message.TextBody);
    
        return Task.FromResult(SmtpResponse.Ok);
}

```

**Comment by pirobox** [comment]
Thank you. I should have figured it out by myself. Too tired...

thank you again.
