### ISSUE TITLE
Accessing the envelope from & to in the save step

### ISSUE THREAD

**Issue by LordMike** [cosullivan/SmtpServer#5]
Hey again,

It just struck me: How do I access the SMTP envelopes From & To properties?

The `IMimeMessage` interface exposes a `From` (single `IMailBox`) and a `To` (list of `IMailBox`) - are these the SMTP from/to?

Maybe they should be named `EnvelopeFrom` and `EnvelopeTo`?

**Comment by LordMike** [comment]
I figured it's the way I described (through tests). Correct me if I'm wrong.

**Comment by cosullivan** [comment]
Yep, the IMimeMessage From and To are from the mail transfer agent (MTA), the actual From and To that the user put in their message will be encoded in the message content. You will need to parse out the message MIME content to access that (I personally use Mail.dll from Limilabs). 

In most cases the From fields will be the same (from the MTA and the encoded MIME content), but the To fields will likely differ. For example, if the user sent a message BCC'd to an address, that address wont show up in the MIME content but it will come through on the IMimeMessage.To field.

**Comment by LordMike** [comment]
Awesome. I use Mimekit - I also reasoned that since you had no MIME parsing stuff (no externals) then you probably didn't have the capability of parsing out the messages to/from.

Now I can do SPF. Awesome. :)
