### ISSUE TITLE
I need AuthenticationRequired to be false when user is coming from localhost only

### ISSUE THREAD

**Issue by HolyOne** [cosullivan/SmtpServer#50]
Hello, Is there a way users can bypass authentication when coming from localhost?
thanks

**Comment by cosullivan** [comment]
Hi, sorry but there is no way to change that behavior as it would mean that the inner state machine would need to be exposed to some level. 

Is there anyway you can control the user name and password from the client if it was local? You can override the authentication mechanism based on the origin of the request such that you always returned true to any username and password combination if the request was from localhost. 

Thanks,
Cain.

**Comment by cosullivan** [comment]
Hi,

I know this is quite late, but I've realised there is an easy solution to this. You should be able to host two instances of the SmtpServer and pass the same filters and message stores to both instances.

The OptionsBuilder actually allows you to specific the IPEndPoint directly so you could create one server with 

  new IPEndPoint(IPAddress.Parse("a.b.c.d"), 9025)

and the other one with

  new IPEndPoint(IPAddress.Parse("127.0.0.1"), 9025)

and with the one bound to localhost, don't configure that to use authentication.

The next version which I am working on is actually allowing this additioanl style configuration on different endpoints running under the same instance.

Thanks,
Cain.
