### ISSUE TITLE
Catch and review email and add some data to its body on server side

### ISSUE THREAD

**Issue by mrjack88** [cosullivan/SmtpServer#51]
I would like to use your SmtpServer to create a sort of 'intermediate' server, that allows me to do some preprocessing, if possible, once i receive emails. I start the server, using this code you provided: 
`var options = new OptionsBuilder()`
   ` .ServerName("localhost")`
    `.Port(25, 587)`
   ` .Build();`

`var smtpServer = new SmtpServer.SmtpServer(options);`
`await smtpServer.StartAsync(CancellationToken.None);`
 but when send an email i got System.IO.IOException and System.Net.Sockets.SocketException.
Can you help me on this. Sorry for the NOOOB question.

**Comment by cosullivan** [comment]
Hi, is it possible that those ports are not accessible or blocked by a firewall?

What is the actual exception message? If you run the same test again, but running as an administrator do you still get the error?

Thanks,
Cain.

**Comment by mrjack88** [comment]
Ok.
 I have disabled firewall. Tried again but same error. Looking at the error message, it's in spanish (my mother tongue) so when translated looks like this: System.Net.Sockets.SocketException: A connection established by your host's software has been aborted. Seems to be that connections are being blocked, but by who (firewall is off).
On the Other hand runnig as admin (the VisualStudio) produces the same result. Running the .exe as standalone, i can't see the output. I will still dig on this to see if i can make it work. Any suggestion would be appreciated

**Comment by cosullivan** [comment]
Ok, what about trying a different port? ie, 9025?

25 and 587 are the standard SMTP ports, so perhaps they are being used or blocked by something else?

**Comment by mrjack88** [comment]
Something weard happen, now when i start the server, everything is ok, and if i do a telnet to localhost 25 it return 220!! I  send an email i does not throw error, but i do not see in console the email's body, as should happen according to this:

`var options = new OptionsBuilder()
    .ServerName("localhost")
    .Port(25, 587)
    .MessageStore(new SampleMessageStore())
    .Build();`

.....

`var message = MimeKit.MimeMessage.Load(textMessage.Content);
        Console.WriteLine(message.TextBody);`

**Comment by cosullivan** [comment]
Are you able to debug/step through your application to ensure that the message store is being called?

**Comment by mrjack88** [comment]
I have a breakpoint in this line:
`var message = MimeKit.MimeMessage.Load(textMessage.Content);`
but I am not able to step through the application, the breakpoint is never hitted.
One question: by passing the new SampleMessageStore() class i guarantee that the method SaveAsync is called? If not where am i supposed to call this function.
I have checked the samples you provided with the project but could not find anything about this.
Thanks for your time.

**Comment by cosullivan** [comment]
Ah, ok - you are using the SampleMessageStore from my samples. This should still be working, but can you try adding Tracing as per this sample;

https://github.com/cosullivan/SmtpServer/blob/master/Src/SampleApp/Examples/SessionTracingExample.cs

This will log all of the commands that are being sent from the client and you will be able hopefully have a better idea of where it is stopping.

Thanks,
Cain.
