### ISSUE TITLE
send email to another smtp server

### ISSUE THREAD

**Issue by pirobox** [cosullivan/SmtpServer#53]
Hi,
    is there any way for taking the incoming mail and send it to another smtp server?

regards, Andrea Pirola

**Comment by cosullivan** [comment]
Hi,

You would need to implement the relay functionality yourself. The SmtpServer component would handle the incoming message, but then you would need to write something that then sent the message to other servers.

Thanks,
Cain.

**Comment by pirobox** [comment]
Hi,
   thank you for the quick answer.
let me help to understand it better. Are you suggesting that I use an
external component that works as an smtp relayer or are you suggesting that
it would be possible to extend cosullivan to do the redirect?

regards,

**Comment by cosullivan** [comment]
Hi,

So this source code (SmtpServer) handles the communication with a Mail Transport Agent (MTA). A MTA 
can be a mail client or another mail server itself passing on the message as a relay server.

You would need to build that functionality yourself, the SmtpServer component here wont be able to cater for that. So what you would have is something like this;

Mail Client => SmtpServer (this source code) => Mail Client => Any other SMTP server.

Given the nature of SMTP communications, if you were to build a relay server (ie, a server that accepts incoming messages and passes them to another server) you would likley need to store the message first in some sort of storage medium such that you can support the ability to retry sending the message on as the other server that you are sending to may not be reachable.

Hope that helps.

Cain.
