### ISSUE TITLE
Communication logs

### ISSUE THREAD

**Issue by Schaussi** [cosullivan/SmtpServer#56]
Hi,

I am looking for the simplest way for saving a full log of communications between 2 servers (HELO, DATA etc.), and assign it to the received message.
So basically I would need the MessageID and another string which contains the whole log for this message (e.g. like it looks via telnet).
Are events like OnSessionCreated, OnCommandExecuting and OnSessionCompleted the right approach to achieve this? 
Or is there maybe an easier "built-in" way to get full logs for the mail transactions?

Thank you!

**Comment by cosullivan** [comment]
Hi,

The SessionCreated, SessionCompleted, and CommandExecuting events are designed for this. You probably want to do something like the following;

https://github.com/cosullivan/SmtpServer/blob/master/Src/SampleApp/Examples/SessionContextExample.cs

The ISessionContext contains a Properties property that is a dictionary of objects that you can use to track with the session. You could use this to track a list of the commands as they are being executed. Additionally, this context is also passed through to the IMessageStore interface which is where you can pull out the Message ID from the MIME content.

Once you have all of that in your session context's property bag, you can do what you like with it during the SessionCompleted event handler.

Thanks,
Cain.

**Comment by Schaussi** [comment]
Hi Cain,

using the session context events, is it possible to get a reference to the actual email message, e.g. get the message's ID in the SessionCompleted event?

Thank you

**Comment by cosullivan** [comment]
Hi,

Yes, but you would have to add the Message ID to the ISessionContext.Properties dictionary yourself in your IMessageStore.

The IMessageStore will give you a Stream of data which is the MIME content. You can then use something like MimeKit to read that MIME stream and it will give you the Message ID. Once you have the Message ID you can do something like;

    context.Properties.Add("Message ID", mime.MessageID);

and that will be available to you in your SessionCompleted event.

Hope that helps.

Thanks,
Cain.

**Comment by Schaussi** [comment]
Works perfectly, thank you!

**Comment by Schaussi** [comment]
Hi cosullivan,
would you please have a quick look at this - if there is no way to get the full log, it's also no big problem.
Thank you

**Comment by cosullivan** [comment]
Hi,

Sorry there is no way to do it at the moment. The SMTP commands are parsed, but only the relevant bits of information are retained on the command object itself.

Thanks,
Cain.
