### ISSUE TITLE
Single DATA line not accepted

### ISSUE THREAD

**Issue by Schaussi** [cosullivan/SmtpServer#58]
Hi,
I just experienced that simple test emails, e.g. with no text or only one line, are not processed.

E.g. this telnet example works fine:
```
...
250 Ok
DATA
354 end with <CRLF>.<CRLF>
asdf
asdf
.

```

Removing one "asdf" line results in a neverending telnet window with no more response:
```
...
DATA
354 end with <CRLF>.<CRLF>
asdf
.

.

```

Could you give me some information about this issue?
Thank you,
best regards

**Comment by cosullivan** [comment]
Hi,

This might be a bug, I shall look into it.

Thanks,
Cain.

**Comment by cosullivan** [comment]
Hi, are you modifying this through Telnet yourself, ie, by backspacing and deleting characters?

This seemed to work fine for me.

**Comment by Schaussi** [comment]
No, I wrote the commands into a usual Win10 cmd/telnet window (without any correction).
I have to write at least 2 lines of DATA before writing the dot.
If the dot is in the second line, it does not get accepted.

**Comment by cosullivan** [comment]
Can you add that cmd script here?

**Comment by Schaussi** [comment]
Sure:
```
220 mail.example.com v4.3.0.0 ESMTP ready
HELO localhost
250 Hello localhost, haven't we met before?
MAIL FROM:<a@b.com>
250 Ok
RCPT TO:<a@b.com>
250 Ok
DATA
354 end with <CRLF>.<CRLF>
asdf
.






bsdf
csdf
.



```
(only modified the hostname in the first line)

**Comment by cosullivan** [comment]
That works for me - the moment I press the enter key after that full stop it responds with
    .
    250 Ok

What version are you using?

**Comment by Schaussi** [comment]
Strange...
I'm using v4.3.0 NuGet package.
Do you work under Linux?
Maybe the return/enter characters are different in the OS, like \r\n, or only \n, ...

**Comment by cosullivan** [comment]
No, I am using Windows.

Can you send me the app that you are using (or a sample of it) to host the server?

**Comment by siewers** [comment]
@Schaussi 
This sounds like the issue I had when hosting in Linux. I made a PR back then, which fixed the issue, and I haven't had it since.
The issue was caused by the SMTP server waiting for an `Environment.NewLine`, which is `\n` on Linux, instead of `\r\n`, so I believe you are on to something with your comment.
I was receiving mails from Exchange, so I knew it would send `\r\n`, but it didn't work.

**Comment by siewers** [comment]
@reinaldocoelho It _was_ a problem, but it got fixed. 
What I'm saying is, that this issue could indicate another similar problem, but I have not encountered it, even though I'm hosting on Linux (Ubuntu in Docker).
The fix I'm referring to is this one https://github.com/cosullivan/SmtpServer/pull/47

**Comment by reinaldocoelho** [comment]
@siewers Understood!
Even a single line DATA need the dot (.) in new line to finish the process.
Maybe the problem could be in the same way.
