### ISSUE TITLE
Final OK message for receiving data

### ISSUE THREAD

**Issue by LordMike** [cosullivan/SmtpServer#6]
Playing around with actual mail systems (Google, Microsoft), I've noticed something: They don't seem to think a mail was safely delivered.

Looking at wireshark, I noticed that there seems to be lacking a final "250 OK" (or similar) from the server after receipt. I tried changing the returned value from `SaveAsync` to be "250 OK", but this value doesn't appear in the TCP stream.

Am I doing something wrong?

**Comment by LordMike** [comment]
Yet again. Bugs on my end. My SaveAsync was taking way too long time, so the other end never got the 250 OK (and the accompanying message).

Sidenote: How can I return something other than OK - in case my save fails, f.ex. due to lacking disk space?

**Comment by cosullivan** [comment]
Previously it assume the return result as a message ID and then formatted the OK response based on that. If there was an exception, then it returned an error.

I've just push a commit that changes the return value of the IMessageStore interface so it now returns an SmtpResponse instead so you can control the response however you like.

By default, return SmtpResponse.Ok.

**Comment by LordMike** [comment]
This should allow me to do my own throttling/timeouts, and then relying on SMTP/MTA's to re-send later.

Thx.
