### ISSUE TITLE
Feature request: any plans to implement RFC 8314 support?

### ISSUE THREAD

**Issue by AndrewGretton** [cosullivan/SmtpServer#60]
[RFC8314](https://tools.ietf.org/html/rfc8314) brings back port 465 for always-encrypted SMTP traffic - something that used to exist, went away, and has now been standardized again. 

I wonder if you could see something like this working:

```
var builder = new OptionsBuilder()
....
.Certificate(GetTheCert())
.Port(25)
.SecurePort(465)
.Build()
```
The implementation would be along the lines of changing `SmtpSessionContext:31` and wrapping the existing stream in an SSLStream created by calling `AuthenticateAsServerAsync` along with the X509 certificate that was also passed in.

**Comment by cosullivan** [comment]
Hi,

I haven't read that RFC but will do so in the next few days. I suspect it's as you suggested and rather trivial to implement in which case I should have it done soon.

Thanks,
Cain.

**Comment by cosullivan** [comment]
Hi @AndrewGretton ,

I've just pushed a branch which support this;
https://github.com/cosullivan/SmtpServer/tree/feature/secure-port

I had to refactor a bit as the state machine needs to operate a bit differently if the session starts as authenticated, but the end result is that you can do

.Port(465, true)

There are a few breaking changes to the OptionsBuilder (now called SmptServerOptionsBuilder) so I will bump the version accordingly and push to NuGet in the coming days.

Thanks,
Cain.
