### ISSUE TITLE
Feature request: force secure connection (TLS)

### ISSUE THREAD

**Issue by rszabolcs** [cosullivan/SmtpServer#61]
Would it be possible to add functionality into SmtpServerOptionsBuilder to enforce usage of forced TLS (and not opportunistic)?

**Comment by cosullivan** [comment]
Hi,

Yes. You can do the following;

.Port(465, true)

which will make it upgrade to an SSL stream during the connection phase. Note that your mail client would also need to support it, and it's usually a connection on port 465.

Thanks,
Cain.

**Comment by rszabolcs** [comment]
Hi,
thank you very much for your quick answer.

Is it not only SSL on connect? We would need force TLS.

**Comment by cosullivan** [comment]
Hi,

I see what you mean now.

I am hesitant to add something like this that isn't included in an RFC. You could do this at present in an IMailboxFilter implementation by checking the ISessionContext.IsAuthenticated property and throwing an SmtpResponseException if it is not. It would achieved the desired outcome.

Additioanlly, with the recent changes I have made I have started exposing more of the internals so the server can be extended easily.

There is a CommandExecuting event that is raised and the event data contains the session context (ISessionContext) which now has a NetworkClient property on it. You can use this to send down a custom response, however the MailCommand would still be executed. I am looking at putting something in place in the future to allow the command to be substituted all together.

Thanks,
Cain.
