### ISSUE TITLE
Develop branch

### ISSUE THREAD

**Issue by mrsaleh** [cosullivan/SmtpServer#62]
Hi
Thank you for your great work. I notice that there is no develop branch and your last commit is WIP.
It is not better to work on develop branch and keep master branch stable.
Best regards.

**Comment by cosullivan** [comment]
Hi, 

Thanks for your feedback.

That last commit was for a minor change to the Readme file, so nothing really that could have caused disruption to the master branch.

As it is only myself doing the development, I haven't felt the need to get too structured in the branches. Whenever I do any work myself I create local branches until everything is working and then I will merge to master and push to Git so the master does stay fairly stable. It would be rare, if at all, that I push unstable code to master.

Thanks,
Cain.
