### ISSUE TITLE
Bcc not find in MimeMessage

### ISSUE THREAD

**Issue by vesnaveen** [cosullivan/SmtpServer#67]
I am using latest version(5.1) smtp server. i have add bcc mail address properly in when i send email from smtp client. but the smtp server could not find bcc address. I have tried from diffrent-2 code. but bcc is not getting me. My code is: 

```
public class SmtpMessageStore : MessageStore
    {      
        public override Task<SmtpResponse> SaveAsync(ISessionContext context, IMessageTransaction transaction, CancellationToken cancellationToken)
        {
            if (context.IsAuthenticated)
            {            
                    var textMessage = (ITextMessage)transaction.Message;
                    MimeMessage message = MimeMessage.Load(textMessage.Content);
		}
	    }
	}
     }	 

```
So what should i do for get bcc address in mime message

**Comment by reinaldocoelho** [comment]
Hi @vesnaveen.

If I understood well, it's not a bug or a problem.
BCC never comes to SmtpServer who receive the message for security reasons, and it would be removed by SmtpServer who send the message.

I hope it help :-)

**Comment by vesnaveen** [comment]
Ok. 
So any option for get BCC ?

**Comment by reinaldocoelho** [comment]
No, becouse SmtpServers who sent EML to you don´t add this information.

**Comment by vesnaveen** [comment]
This is big issue for us ,beacause we have provide option for cc and bcc in our service. and when is send via WebApi, Cc and Bcc both are wokring properly. 
If this server will not allow Bcc address, So we will have to move on another Smtp server. So if you have another reference or solution regarding Bcc Address , Please help us

**Comment by reinaldocoelho** [comment]
I understand, but I think you not will find any SmtpServer to receive messages who will give to you this information.

Who sent this BCC information is the sender (SmtpServer), and if you not control the sender (to create an EML with this information, and it will be an mistake for security and privacity reasons), you will not receive that.

Maybe @cosullivan  can give to you some suggestions.

**Comment by cosullivan** [comment]
Hi @vesnaveen, @reinaldocoelho is correct here in that the Mime content will **not** contain any BCC addresses as that would default the whole purpose of the BCC field. 

The addresses that are included inside the Mime content and those addresses that are passed to the SMTP server during the RCPT TO command can and will be different. The SMTP server has no knowledge of the contents of the message body.

The complete list of email addresses are available to you through the IMessageTransaction.To property here;
https://github.com/cosullivan/SmtpServer/blob/master/Src/SmtpServer/IMessageTransaction.cs#L16

Say for example that you wanted to send an email to **a@abc.com** and **a@def.com** and both of these are included in the **To** field of the message. The MIME content will contain both of these addresses, however, the mail server for **abc.com** will only receipt a single email address in the **RCPT TO** command for **a@abc.om** and the def.com mail server will only receive a single email address in the **RCPT TO** command for **a@def.com**.

Extending this example, if **a@def.com** was included as a **BCC** recipient then both servers will still receipt their addresses as above via the **RCPT TO** command, however the **MIME** content is only going to include a single address as the **BCC** should be omitted. 

I hope this makes sense.

Thanks,
Cain.
