### ISSUE TITLE
Question about example and documentation.

### ISSUE THREAD

**Issue by aap4ixx** [cosullivan/SmtpServer#68]
Hi,

First: big thanks for you project. Project is very god and bring the people benefits.
Second: But at this moment i can find normal documentation about you project (no example, no documentation).
May be i trying to find the wrong place?
At this moment i find small info in you Wiki and in the project "SmtpServer.Tests".

**Comment by cosullivan** [comment]
Hi,

At the moment the only documentation I have exists in the samples here;
https://github.com/cosullivan/SmtpServer/tree/master/Src/SampleApp/Examples

I am planning on writing some documentation but just haven't gotten around to it yet.

Thanks,
Cain.

**Comment by aap4ixx** [comment]
Sorry for delay.
I will try use you example, if i not found any example a will write here.
Big thanks for information and you project.
