### ISSUE TITLE
TLS 1.2

### ISSUE THREAD

**Issue by tfrost** [cosullivan/SmtpServer#76]
I successfully built a mail server using the SmtpServer version downloaded at the end of March this year.  But https://starttls-everywhere.org reports that it does not support TLS1.2.  What is the best way to resolve this?  Can I simply substitute a MailKit 1.22 or later?  Or even MailKit 2.0?  Are any changes needed in SmtpServer to support TLS1.2?

**Comment by cosullivan** [comment]
Hi,

The default TLS is 1.0, I will look to change this in the future.

If you want to change it you can use the SupportedSslProtocols method on the SmtpServerOptionsBuilder and set it to SslProtocols.Tls12.

Thanks,
Cain.

**Comment by tfrost** [comment]
Thanks,  that worked; I switched to 1.22 for Mailkit and MimeKit and also changed Default to SslProtocols.Tls | SslProtocols.Tls11 | SslProtocols.Tls12
