### ISSUE TITLE
(Feature) Message Filter

### ISSUE THREAD

**Issue by jjxtra** [cosullivan/SmtpServer#78]
The mailbox filter is great, however a message filter is needed to deal with spam or rules based messages. This message filter would run before the message store filter, and after the mailbox filter.

**Comment by cosullivan** [comment]
Hi,

I will have a look into the feasibility of this but I suspect that would be called at the exact same time as the Message Store anyway.

For now you could abstract this into building a CompositeMessageStore (as per the CompositeMailboxFilter) and adding two Message Stores yourself. If the first one through an SmtpResponseException then that would mimic the behavior close to what the implementation of the feature would do.

Thanks,
Cain.
