### ISSUE TITLE
How do Send Message 

### ISSUE THREAD

**Issue by MohMehrnia** [cosullivan/SmtpServer#84]
how do send message with created server??
i used below code but not work
```
SmtpClient smtpClient = new SmtpClient();
            smtpClient.Host = "localhost";
            smtpClient.Port = 587;
            smtpClient.Send(new MailMessage("app@AIKI.CO.ir", "qermezkon@gmail.com")
            {
                Subject = "Test",
                Body = "test"
            });
```

**Comment by cosullivan** [comment]
Hi,

How have you configured the server? ie, what port, filters, etc? 

Can you reference the examples here;
https://github.com/cosullivan/SmtpServer/tree/master/Src/SampleApp/Examples

Thanks,
Cain.

**Comment by Nemo2478** [comment]
Hello Cain,

I opened the ports but the same code of MohMehrnia don't work for me.

Regards and thanks

**Comment by cosullivan** [comment]
Hi @Nemo2478 ,

Please have a look at this sample to enable tracing;
https://github.com/cosullivan/SmtpServer/blob/master/Src/SampleApp/Examples/SessionTracingExample.cs

And see whether you get any trace events happening?

Thanks,
Cain.

**Comment by Nemo2478** [comment]
Hello @cosullivan ,

I don't understand now. I have the following code:

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using SmtpServer;
using SmtpServer.Tracing;

namespace E_Mail_Server
{
    class Program
    {
        static CancellationTokenSource _cancellationTokenSource;

        static void Main(string[] args)
        {
            StartAsync().Wait();
        }

        public static async Task StartAsync()
        {
            _cancellationTokenSource = new CancellationTokenSource();

            var options = new SmtpServerOptionsBuilder()
                .ServerName("localhost")
                .Port(25, 587)
                .Build();
            var server = new SmtpServer.SmtpServer(options);

            server.SessionCreated += OnSessionCreated;
            server.SessionCompleted += OnSessionCompleted;

            var serverTask = server.StartAsync(_cancellationTokenSource.Token);

            serverTask.WaitWithoutException();
        }

        static void OnSessionCreated(object sender, SessionEventArgs e)
        {
            Console.WriteLine("SessionCreated: {0}", e.Context.RemoteEndPoint);

            e.Context.CommandExecuting += OnCommandExecuting;
        }

        static void OnSessionCompleted(object sender, SessionEventArgs e)
        {
            Console.WriteLine("SessionCompleted: {0}", e.Context.RemoteEndPoint);

            e.Context.CommandExecuting -= OnCommandExecuting;

            _cancellationTokenSource.Cancel();
        }
    }
}
```

But Visual Studio tell me the following: 

> "Task" don't contains a definition for "WaitWithoutException", and no WaitWithoutException-Method could be found that accept a first argument of type "Task" (there may be a missing using-directive or an Assembly-Reference).

Regards and thanks

Nemo

**Comment by cosullivan** [comment]
Hi,

This is included as an extension method here;
https://github.com/cosullivan/SmtpServer/blob/master/Src/SampleApp/TaskExtensions.cs

Thanks,
Cain.

**Comment by Nemo2478** [comment]
Hello cosullivan,

My code, now, is this:

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using SmtpServer;
using SmtpServer.Tracing;

namespace E_Mail_Server
{
    public static class Program
    {
        static CancellationTokenSource _cancellationTokenSource;

        static void Main(string[] args)
        {
            StartAsync().Wait();
        }

        public static async Task StartAsync()
        {
            _cancellationTokenSource = new CancellationTokenSource();

            var options = new SmtpServerOptionsBuilder()
                .ServerName("localhost")
                .Port(25, 587)
                .Build();
            var server = new SmtpServer.SmtpServer(options);

            server.SessionCreated += OnSessionCreated;
            server.SessionCompleted += OnSessionCompleted;

            var serverTask = server.StartAsync(_cancellationTokenSource.Token);

            WaitWithoutException(serverTask);
        }

        static void OnSessionCreated(object sender, SessionEventArgs e)
        {
            Console.WriteLine("SessionCreated: {0}", e.Context.RemoteEndPoint);

            e.Context.CommandExecuting += OnCommandExecuting;
        }

        static void OnSessionCompleted(object sender, SessionEventArgs e)
        {
            Console.WriteLine("SessionCompleted: {0}", e.Context.RemoteEndPoint);

            e.Context.CommandExecuting -= OnCommandExecuting;

            _cancellationTokenSource.Cancel();
        }

        static void OnCommandExecuting(object sender, SmtpCommandExecutingEventArgs e)
        {
            new TracingSmtpCommandVisitor(Console.Out).Visit(e.Command);
        }

        public static void WaitWithoutException(this Task task)
        {
            try
            {
                task.Wait();
            }
            catch (AggregateException e)
            {
                e.Handle(exception => exception is OperationCanceledException);
            }
        }
    }
}
```

En this are the trace events I got:

> SessionCreated: 127.0.0.1:49510
> EHLO: DomainOrAddress=X61s-PC
> MAIL: Address=app@AIKI.CO.ir Parameters=
> RCPT: Address=nemoschmidt7@gmail.com
> DATA

But after a time the console closes. The Exit-Report is this:

> Exception triggered: "System.OperationCanceledException" in SmtpServer.dll
> Exception triggered: "System.OperationCanceledException" in mscorlib.dll
> Exception triggered: "System.OperationCanceledException" in SmtpServer.dll
> Exception triggered: "System.ObjectDisposedException" in System.dll
> Exception triggered: "System.OperationCanceledException" in mscorlib.dll
> Exception triggered: "System.OperationCanceledException" in mscorlib.dll
> Exception triggered: "System.ObjectDisposedException" in System.dll
> Exception triggered: "System.AggregateException" in mscorlib.dll
> The program "[8000] E-Mail Server.exe" has ended with code 0 (0x0).

Regards and thanks

**Comment by cosullivan** [comment]
Hi,

I would suspect that for some reason your mail client is not sending the actual message or at least the message has not been read completely and thus the network client is timing out and cancelling the operation;
https://github.com/cosullivan/SmtpServer/blob/master/Src/SmtpServer/Protocol/DataCommand.cs#L37

Thanks,
Cain.

**Comment by Nemo2478** [comment]
Hello cosullivan,

And can I avoid that the network client cancel the operation? How?

Regards and thanks

**Comment by cosullivan** [comment]
No, but why would you want to? The mail client should start sending the data?

How long before it cancels?

**Comment by Nemo2478** [comment]
I want to avoid that the network client cancel the operation to send an E-Mail. The mail client should start sending the data by pressing a button. 
Approximately two minutes before the console closes.

**Comment by cosullivan** [comment]
Please try increasing the timeout then, the default is 2 minutes.

    var options = new SmtpServerOptionsBuilder()
        .ServerName("localhost")
        .Port(25, 587)
        .NetworkBufferReadTimeout(TimesSpan.FromMinutes(30))
        .Build();

**Comment by Nemo2478** [comment]
Hello cosullivan,

I did it but the E-Mail was not sent or not received... :( What else can I do?

Regards and thanks

**Comment by cosullivan** [comment]
Hi,

Well if it wasn't sent then that would explain why it wasn't received :-)

Without seeing any code its hard to help any further, however that read timeout is applied to the underlying stream so in theory that should control how long the stream waits before timing out reading data. 

Thanks,
Cain.

**Comment by Nemo2478** [comment]
Hello cosullivan,

But... I showed you my code.
What are you meaning with "read timeout"?

Regards and thanks

**Comment by farshid3003** [comment]
I have the same problem 
```
SessionCreated: 127.0.0.1:59082
EHLO: DomainOrAddress=127.0.0.1
AUTH: Method=Plain, Parameter=AGNhaW4AbydzdWxsaXZhbg==
MAIL: Address=from@sample.com Parameters=
RCPT: Address=to@sample.com
DATA
MAIL: Address=from@sample.com Parameters=
RCPT: Address=to@sample.com
DATA
MAIL: Address=from@sample.com Parameters=
RCPT: Address=to@sample.com
DATA
MAIL: Address=from@sample.com Parameters=
RCPT: Address=to@sample.com
DATA
MAIL: Address=from@sample.com Parameters=
RCPT: Address=to@sample.com
DATA
QUIT
SessionCompleted: 127.0.0.1:59082
```

no data without exception
please let me know what is this :
`client.ReadUntilAsync(new byte[] { 13, 10, 46, 13, 10 }`

I have another question 
I get the email in this server and I want to change some staffs in the message body and then send it by my system. 
dose this server automatically send the email to the destination ?
where is the best place to get the message and finish the request for me ?

Best Regards
