### ISSUE TITLE
The Console-Application closes

### ISSUE THREAD

**Issue by Nemo2478** [cosullivan/SmtpServer#85]
Hello cosullivan,

I used the following code:

```
var options = new SmtpServerOptionsBuilder()
    .ServerName("localhost")
    .Port(25, 587)
    .Build();

var smtpServer = new SmtpServer.SmtpServer(options);
await smtpServer.StartAsync(CancellationToken.None);
```

But when I want to start the console, it opens and closes.

In the Exit-Report, it release me this:

> "E-Mail Server.exe" (CLR v4.0.30319: DefaultDomain): "C:\Windows\Microsoft.Net\assembly\GAC_32\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll" loaded. The loading symbols was skiped. The module is optimized, and the option of debug "Only own code" is activated.
> "E-Mail Server.exe" (CLR v4.0.30319: DefaultDomain): "C:\Users\X61s\source\repos\E-Mail Server\E-Mail Server\bin\Debug\E-Mail Server.exe" loaded. The symbols have been loaded.
> "E-Mail Server.exe" (CLR v4.0.30319: E-Mail Server.exe): "C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll" loaded. The loading symbols was skiped. The module is optimized, and the option of debug "Only own code" is activated.
> "E-Mail Server.exe" (CLR v4.0.30319: E-Mail Server.exe): "C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll" loaded. The loading symbols was skiped. The module is optimized, and the option of debug "Only own code" is activated.
> "E-Mail Server.exe" (CLR v4.0.30319: E-Mail Server.exe): "C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll" loaded. The loading symbols was skiped. The module is optimized, and the option of debug "Only own code" is activated.
> "E-Mail Server.exe" (CLR v4.0.30319: E-Mail Server.exe): "C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll" loaded. The loading symbols was skiped. The module is optimized, and the option of debug "Only own code" is activated.
> The program "[5820] E-Mail Server.exe" ended with the code 0 (0x0).

Then I thought it was because the option of debug "Only own code" was activated; so I deactivated it and I started the console again and then the same thing happens again (The console opens and closes) and the Exit-Report release me this:

> "E-Mail Server.exe" (CLR v4.0.30319: DefaultDomain): "C:\Windows\Microsoft.Net\assembly\GAC_32\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll" loaded. The PDB-File was not found can not be opened.
> "E-Mail Server.exe" (CLR v4.0.30319: DefaultDomain): "C:\Users\X61s\source\repos\E-Mail Server\E-Mail Server\bin\Debug\E-Mail Server.exe" loaded. The symbols have been loaded.
> "E-Mail Server.exe" (CLR v4.0.30319: E-Mail Server.exe): "C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll" loaded. The PDB-File was not found can not be opened.
> "E-Mail Server.exe" (CLR v4.0.30319: E-Mail Server.exe): "C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll" loaded. The PDB-File was not found can not be opened.
> "E-Mail Server.exe" (CLR v4.0.30319: E-Mail Server.exe): "C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll" loaded. The PDB-File was not found can not be opened.
> "E-Mail Server.exe" (CLR v4.0.30319: E-Mail Server.exe): "C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll" loaded. The PDB-File was not found can not be opened.
> The program "[5820] E-Mail Server.exe" ended with the code 0 (0x0).

Bye and thanks

PS.: The code of my application of console is this:

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using SmtpServer;

namespace E_Mail_Server
{
    class Program
    {
        static void Main(string[] args)
        {
            StartAsync();
        }

        public static async void StartAsync()
        {
            var options = new SmtpServerOptionsBuilder()
                .ServerName("localhost")
                .Port(25, 587)
                .Build();
            var smtpServer = new SmtpServer.SmtpServer(options);
            await smtpServer.StartAsync(CancellationToken.None);
        }
    }
}
```

**Comment by cosullivan** [comment]
Hi,

You are calling StartAsync() in your Main and have nothing to wait for it to complete - that method is effectively returning to the Main method as soon as you call the "await".

Try this instead.

    static void Main(string[] args)
    {
        StartAsync().Wait();
    }

    public static async Task StartAsync()
    {
        var options = new SmtpServerOptionsBuilder()
            .ServerName("localhost")
            .Port(25, 587)
            .Build();
            var smtpServer = new SmtpServer.SmtpServer(options);
            await smtpServer.StartAsync(CancellationToken.None);
    }

Thanks,
Cain.

**Comment by Nemo2478** [comment]
Hello Cain,

the console don't closes anymore.

Thanks for your help
