### ISSUE TITLE
Bot mail server

### ISSUE THREAD

**Issue by OmidID** [cosullivan/SmtpServer#86]
I want to create a Bot mail server and do you think your project is ok for that?
As I understand with one custom MessageStore I can do that. Right?

**Comment by cosullivan** [comment]
Hi, 

I'm not sure what a Bot mail server is but yes you can pretty much do anything you want in the IMessageStore implementation, ie, store it, forward it on, etc.

Thanks,
Cain.

**Comment by OmidID** [comment]
Actually I need a functionality to know sender, receiver, body and subject to reply a main to the sender. I don't want to store any email. 
I need to receive from any email address on a specific domain, ex: *@my-domain.com
Thank you so much.
