### ISSUE TITLE
Make SmtpSessionContext.Properties thread safe

### ISSUE THREAD

**Issue by siewers** [cosullivan/SmtpServer#87]
I don't know if it's an actual issue or just me doing something wrong, but, the `Properties` dictionary on the `SmtpSessionContext` is not thread safe.
In my current use case, I need to keep track of the number of messages I've processed during a transaction. 
To do that, I increment a value in the properties dictionary for each message I process. Because two messages can access the dictionary at the same time, the message number could be the same.
https://github.com/cosullivan/SmtpServer/blob/44a5e190283eedf602dad458bbe213d37ca978ea/Src/SmtpServer/SmtpSessionContext.cs#L87

Am I doing it wrong or should/could the `Properties` property be changed to a `ConcurrentDictionary`?

**Comment by cosullivan** [comment]
Hi,

I can change that to a ConcurrentDictionary, but how are you getting multiple messages access it at the same time?

A new session context should be created for each session and typically a mail client would send messages sequentially. 

Are you sending messages in parallel on the same connection?

Thanks,
Cain.

**Comment by siewers** [comment]
As I said, I don't know if I'm doing something wrong, but when I receive BCC's it seems like I have the same transaction, but multiple messages. I couldn't find any oyher solution than keep track of the message number to solve that.

**Comment by siewers** [comment]
Just to be sure you understand, I am not saying this is a bug in the SmtpServer project, it _might_ be an issue on my side. If you say that it shouldn't be possible to have two messages with the same transaction, I am most certainly doing something wrong here, but I need to make sure of that :)

**Comment by cosullivan** [comment]
Yeah, it would be unusual if it allowed you to received multiple messages simultaneously as there is a state machine that is assigned to each session and this shouldn't allow inconsistent states.

Have a look at this sample;
https://github.com/cosullivan/SmtpServer/blob/master/Src/SampleApp/Examples/SessionTracingExample.cs

and turn on command level tracing if you can and then you can see exactly what commands are being executed by the server.

**Comment by cosullivan** [comment]
It's hard to know what the server will be sending, but in theory after the DATA command has completed (ie, the message has been received) the state machine will transition back to the WaitingForMail state and the MTA can then send another message, however the previous transaction itself should then be reset.

https://github.com/cosullivan/SmtpServer/blob/master/Src/SmtpServer/Protocol/MailCommand.cs#L36

**Comment by siewers** [comment]
I just did a test from Office 365 using a connector.
I sent a single message with one **to** and one **bcc**.
What Office 365 is doing is sending _two_ messages - one message sent to the **to** and one sent to the **bcc**.
Both messages are identical and in the _same_ transaction (with different recipients of course).

Is that to be expected or a bug?
If it's expected, my assumption about potentially having a thread safety issues could be correct, right?

What's interesting is that I am getting the **bcc** before the **to**.
Trace:
```
2018-09-10 17:34:32 VRB EHLO: DomainOrAddress="EUR01-DB5-obe.outbound.protection.outlook.com"
2018-09-10 17:34:32 VRB STARTTLS
2018-09-10 17:34:32 VRB EHLO: DomainOrAddress="EUR01-DB5-obe.outbound.protection.outlook.com"
2018-09-10 17:34:32 VRB MAIL: Address="<REDACTED>" Parameters={}
2018-09-10 17:34:32 VRB RCPT: Address="test2@mailinator.com"
2018-09-10 17:34:32 VRB DATA
.
.
.
2018-09-10 17:34:35 VRB MAIL: Address="<REDACTED>" Parameters={}
2018-09-10 17:34:35 VRB RCPT: Address="test1@mailinator.com"
2018-09-10 17:34:35 VRB DATA
2018-09-10 17:34:35 VRB Message processing started.
.
.
.
2018-09-10 17:34:36 VRB QUIT
```

**Comment by cosullivan** [comment]
Ok, it's unusual that they send the BCC's separately but its still perfectly valid. 

The output log shows that the messages are being sent sequentially which is good and therefore you shouldn't really have any concurrency issues. 

We might also be using different terminology here which could be a source of confusion. For me,  messages above are in the same _session_ but they are _different_ transactions. The session is tracked for the lifetime of the connection (from the HELO/EHLO to the QUIT command) and the transaction boundary is from the MAIL command to the end of the DATA command. Internally the same IMessageTransaction instance is used for both but the transaction is reset at the start of the MAIL command.

Are you modifying the session properties from within the IMessageStore.SaveAsync method? If you are calling any further async methods from within here then perhaps these aren't being awaited? 

If you are able to share some more code or an example to reproduce then I am happy to help debug it further.

**Comment by siewers** [comment]
Oh yes, you are right. It's _session_ I meant.

I am modifying the session properties within the `SaveAsync` method.
The only issue I'm having is that I actually _don't know_ if it's an issue at all. I just saw the behavior (a _single_ case) which _could_ be caused by the dictionary not being thread safe, that is, two messages doing `TryGetValue` at the same time, making both messages the first one.
I know it would be rare, which is why I'm very hesitant to blame anything, except my own code :).

Basically what I've done is create an extension method which can update a value in the properties dictionary like so:
```
public static TValue GetOrUpdatePropertyValue<TValue>(this ISessionContext sessionContext, string key, Func<TValue, TValue> valueUpdater)
{
    sessionContext.TryGetPropertyValue(key, out TValue value);

    TValue newValue = valueUpdater(value);
    sessionContext.Properties[key] = newValue;

    return newValue;
}

private static bool TryGetPropertyValue<TValue>(this ISessionContext sessionContext, string key, out TValue value)
{
    if (sessionContext.Properties.TryGetValue(key, out object propertyValue))
    {
        value = (TValue) propertyValue;

        return true;
    }

    value = default;

    return false;
}
```

When I receive a message, I then increment the message number like this:
```
int messageNumber = context.GetOrUpdatePropertyValue(emailMessageDescriptor.MessageId, (int number) => number + 1);
```

Later on, I just do a check to see if the `messageNumber` is equal to `1` and if so, treat it as the first message.

I cannot reveal my specific use-case, but this is what I _think_ could be the problem.

Also, I could just put a lock around the dictionary access, but that would only solve the alleged problem for me
