### ISSUE TITLE
.NET Core

### ISSUE THREAD

**Issue by LordMike** [cosullivan/SmtpServer#9]
Hey,

I was looking into migrating the SmtpServer projects to Core. And most of it is just easy-peasy straight ahead. I've discovered issues with a few things:
- TcpClient doesn't expose a public `Close()` or `Dispose()` (which I find odd) in `netcoreapp1.0`
- The `SslProtocols` doesn't have a `Default` member
- I'm unsure how the Ssl part will work, as Linux doesn't have a certificate store... 
- It is not possible to get `Assembly` from a Type (it's now a `TypeInfo`)

I could commit my changes, if it were something of interest?

**Comment by LordMike** [comment]
Edit: I figured out the Dispose thing .. Apparently the TcpClient implemented `IDisposable` like this:

`public IDisposable.Dispose()` .. Meaning I had to call it like this: `((IDisposable)_tcpClient).Dispose();`

**Comment by cosullivan** [comment]
Great.

I haven't converted anything to Core yet. How does it work from a VS build & nuget packing situation? Does it become a separate project in the VS solution that targets Core?

**Comment by LordMike** [comment]
Hi,
 
No it's much, much simpler.
 
What you do is you replace the entire project (s) with .net core versions (after upgrading VS to 2015 update 3).
 
Then your development environment is pretty much the same. You can build, develop and debug as you used to.
 
The good stuff comes in targeting. You target, from the same project, all the environments you want, and VS will then only present you with intellisense etc that matches all environments.
 
For packing, there's a “dotnet pack” command which will build a nuget package with all the final binaries in it (set up correctly so that any consumer will be able to use it from any of their projects).
 
For reference you can check out the project.json and the nuger feed for my other project: TMDbLib at lordmike/tmdblib and the same on Nuget.
 
There are some caveats. While you can target the regular .net frameworks, the entire ecosystem around corner core isn’t done yet. F.ex. Microsoft will replace the project.json with the old .csproj again in their next release, which should come around Q4. The IDE experience is also not complete, as you f.ex. Can't reference a core project from non-Core projects..

**Comment by reinaldocoelho** [comment]
Hi there.

I created a PullRequest with conversion to DotNet Core.

I hope it´s help to final conversion :-)

Thanks for the great project.

**Comment by MaitreDede** [comment]
Hi :)

I have also made an attempt to port to dotnet core. See PR #15.

In the next steps, I think I will add support for dependency injection and logging (through microsoft's extension packages).

**Comment by cosullivan** [comment]
Thanks.

 

I merged that PR, but ended up converting the other projects back to Net45 for now as I had heaps of issues building – not sure what the problem was, but I will convert them later. The Main SmtpServer now builds and packages as .NETFramework 4.5 and .NETStandard 1.6.
