### ISSUE TITLE
Consider making SmtpSession public

### ISSUE THREAD

**Issue by robeving** [cosullivan/SmtpServer#91]
Currently SmtpSession is internal, meaning that the only way to access it is via SmtpServer which manages the TCP listener.

I have an existing solution which already manages TCP listeners, gives metric on connections etc. I would like to use this instead of SmtpServer. If SmtpSession was public I could.

**Comment by robeving** [comment]
It effectively replaces SmtpServer.cs with a similar one that provides connection statistics, changes some of the properties of the TcpClient as well as fires callbacks when connections are made.

An interface wouldn't work for me as I want to be the owner of the TcpListener.

**Comment by cosullivan** [comment]
Hi @robeving ,

I've pushed some changes to a feature branch that I think might allow you to solve your problem without making the SmtpSession public.

The change now extracts all of the functionality that the SmtpServer requires from the TcpListener and will allow customization.

See the changes here;
https://github.com/cosullivan/SmtpServer/tree/feature/external-listener/Src/SmtpServer/Net

Effectively this would allow you to create your own implementation of ITcpListenerFactory (can you see its very simple) and thus you would have complete control over the underlying TcpListener and thus you could modify the TcpClient in anyway you see fit. 

Please let me know if you think this would allow you to solve your requirements.

Thanks,
Cain.
