### ISSUE TITLE
Attachments are not received completely

### ISSUE THREAD

**Issue by Letalis82** [cosullivan/SmtpServer#92]
Hi I'm using the MessageStore example.

To store the attachment in the message i'll used the following example:
`foreach (var attachment in message.Attachments)
            {
                using (var memory = new MemoryStream())
                {
                    if (attachment is MimePart)
                        ((MimePart)attachment).Content.DecodeTo(memory);
                    else
                        ((MessagePart)attachment).Message.WriteToAsync(memory);
                    var bytes = memory.ToArray();
                    File.WriteAllBytes(@"c:\tmp\mailDump\" + Guid.NewGuid().ToString(), bytes);
                }
            }`

When a single message comes in the entire message is stored (incl the complete attachment). When a bulk of messages is comming in, none of the attachments are stored completely. 
The message i use for testing is with an attachment of 7mb. Most of the time it doesnt store more then 500kb to 2mb

**Comment by cosullivan** [comment]
Hi,

Based on your code sample there the first thing that stands out is that you are not awaiting on the WriteToAsync method. That could very much explain the issue you are seeing.

Can you first change your code to be an async method and await on that WriteToAsync call
    else await ((MessagePart)attachment).Message.WriteToAsync(memory); 

and see if you still have the same problem?

Thanks,
Cain.

**Comment by Letalis82** [comment]
Hi Cain, 

Thanks for your reply.

Ik adjusted it to the following:
![image](https://user-images.githubusercontent.com/45654542/49637711-77b68c00-fa06-11e8-88e8-d02b71180fd9.png)

Unfortunately it has the same problem. When i break in the SaveAsync method it look that the attachment there is already incomplete.

**Comment by cosullivan** [comment]
Hi,

I still think you probably have an issue in your use of async/await here.

I can't edit that because it's a screenshot so hopefully I can list the changes.

1. Make the SaveAsync method async, ie, 

    `public override async Task<SmtpResponse> SaveAsync(...`

    and the method should then return 

    `return SmtpResponse.Ok;`

2. Instead of using 

    `new Task(() => SaveFile(message)).Start() `

    do the following

    `await SaveFile(message);`

3. Change the return type of SaveFile from void to `Task`

And see how that goes?

Thanks,
Cain.

**Comment by Letalis82** [comment]
Hi,

It looks like the same problem.

I changed it to the following:
` public override async Task<SmtpResponse> SaveAsync(ISessionContext context, IMessageTransaction transaction, CancellationToken cancellationToken)
        {
            var textMessage = (ITextMessage)transaction.Message;

            var message = MimeKit.MimeMessage.Load(textMessage.Content);

            await SaveFile(message);

            Console.WriteLine($"{message.TextBody} ");

            return SmtpResponse.Ok;
        }

        private async Task SaveFile(MimeMessage message)
        {
            foreach (var attachment in message.Attachments)
            {
                using (var memory = new MemoryStream())
                {
                    if (attachment is MimePart)
                    { await ((MimePart)attachment).Content.DecodeToAsync(memory); }
                    else
                    { await ((MessagePart)attachment).Message.WriteToAsync(memory); }

                    var bytes = memory.ToArray();

                    await File.WriteAllBytesAsync(@"c:\tmp\mailDump\" + Guid.NewGuid().ToString(), bytes);
                }
            }
        }`

The main class:
`class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Starting Smtp server");

            new Starter().StartAsync().Wait();
        }

        
    }

    public class Starter
    {
        public async Task StartAsync()
        {
            var cancellationTokenSource = new CancellationTokenSource();

            var options = new SmtpServerOptionsBuilder()
                .ServerName("SmtpServer SampleApp")
                .Port(1000)
                .MessageStore(new TestMessageStore())
                .Build();

            var server = new SmtpServer.SmtpServer(options);
            await server.StartAsync(cancellationTokenSource.Token);
        }
    }`

**Comment by cosullivan** [comment]
Hi,

If you can send me a sample application (including message) that reproduces this issue then I can take a look.

Thanks,
Cain.

**Comment by cosullivan** [comment]
Hi,

Ok so the issue is in how you are sending the messages.

In Form1.cs, do the following;

1. Instead of this

    `private async void CreateMessage(MimeMessage message)`

    do this

    `private async Task CreateMessage(MimeMessage message)`

2. Instead of this

    ```
    new Task(() =>
                    {
                        CreateMessage(message);
                    }).Start();
    ```

    do this

    `await CreateMessage(message);`

You need to be careful about how you are using async functions, especially with having anything that is `async void` . Probably the only place this is accepted is via an event handler as per your button click event. 

Thanks,
Cain.

**Comment by Letalis82** [comment]
Fantastic!

That did the trick. Thanks for your help!

Cheers
