### ISSUE TITLE
Why `Stream` property is on `ITextMessage` and not on `IMessage`?

### ISSUE THREAD

**Issue by ramonsmits** [cosullivan/SmtpServer#93]
Why `Stream` property is on `ITextMessage` and not on `IMessage`? I would think that any message would have atleast a stream.

Also, currently there is only one message type. I would suggest refactoring this code away until there actually are multiple implementations.

I can provide a PR if wanted.

**Comment by cosullivan** [comment]
Hi @ramonsmits,

The `Stream` property is on the `ITextMessage` interface as opposed to `IMessage` for cases when the `IMessage` itself was pre-processed into something more meaningful. 

For example, at one point I was actually making an `IMimeMessage` of which it had a property of `MimeDocument`;
https://github.com/cosullivan/SmtpServer/blob/feature/3.1.0.0-MIME/Src/SmtpServer.Mime/Mail/IMimeMessage.cs

I shelved that branch when I realized how much work there would be when MimeKit does such a good job of handling MIME anyway. I was planning on switching that branch across to using MimeKit but didn't end up proceeding. 

I guess that code probably can be removed for now so go ahead and create a PR.

Thanks,
Cain.
