### ISSUE TITLE
Messages not being sent

### ISSUE THREAD

**Issue by gigajew** [cosullivan/SmtpServer#95]
This is what I get in the console. No messages sent.

SessionCreated: *.*.*.*:55552
EHLO: DomainOrAddress=DESKTOP-*******
MAIL: Address=**********@gmail.com Parameters=
RCPT: Address=**********@dispostable.com
DATA

**Comment by cosullivan** [comment]
Hi,

You will need to provide some more information if you would like assistance on this. 

Are you running one of the samples, or have you created your own app where you are seeing this? This appears an issue in that the client isn't sending the data.

Thanks,
Cain.

**Comment by gigajew** [comment]
I'm using smtpclient without SSL. What information do you need?

**Comment by cosullivan** [comment]
A sample application demonstrating the issue you are seeing.

Can you also run the following;
https://github.com/cosullivan/SmtpServer/blob/master/Src/SampleApp/Examples/SimpleExample.cs

and see if that works?

**Comment by gigajew** [comment]
That would be the git version, I'll run this git example on the nuget version and post the result

**Comment by gigajew** [comment]
Server: https://pastebin.com/HyGWZPQw
Client: https://pastebin.com/GfCZDm74
Server log: https://pastebin.com/A165X7br
And no mail in the mailbox

**Comment by cosullivan** [comment]
Are you expecting a message to be sent to the testme@dispostable.com account?

I can only deduce from limited information that you are expecting it to operate as an open relay server , however that is not the purpose of this component. 

When the message has been received it will make a call to the `IMessageStore` implementation that has been configured. By default, if you don't configure one it uses the DoNothingMessageStore instance (which as the name suggests, does nothing);
https://github.com/cosullivan/SmtpServer/blob/master/Src/SmtpServer/SmtpServerOptionsBuilder.cs#L23

If you want it to act as an open relay server you would need to build that logic into an implementation of IMessageStore.

**Comment by gigajew** [comment]
Oh I thought this was just kinda like a standalone mail server
